### ISSUE TITLE
Possible bug in calculation of Positively Selected Sites

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#101]
- Last modified: Wed Feb 13, 2019  10:27AM
- Sign: JN

## Description

Possible bug in calculation of Positively Selected Sites.

According to older version of the Manual, the result of the commands below should give (MrBayes manual, section **Identifying Positively Selected Sites**):

    Examination of the positive selection probabilities and codon site omega
    values reveals which sites are most likely to be experiencing positive selection.
    For instance, the evidence is strong that site (292,293,294) is under positive
    selection (\ttt{pr+(292,293,294) = 0.998}, \ttt{omega(292,293,294) = 1.21}).

When reanalyzing the same data (Feb 2019), no pr+ values are above 0.282567.
Furthermore, for site (292,293,294), we get pr+(292,293,294) = 0.000015, omega(292,293,294) = 0.070020.

## To reproduce

- mb v.3.2.7 develop branch. Feb 2019.
- Need file `https://github.com/NBISweden/MrBayes/blob/develop/examples/replicase.nex`
- MrBayes commands:

        #NEXUS
        begin mrbayes;
          set seed=54321 swapseed=54321;
          execute replicase.nex;
          lset nucmodel=codon omegavar=ny98;
          report possel=yes siteomega=yes;
          mcmcp printfreq=20 samplefreq=20 diagnfreq=500;
          mcmc ngen=1000000;
          sump;
        end;

**Comment by nylander** [comment]
See also #46 !

**Comment by ronquist** [comment]
This is a bug in MrBayes versions up to version 3.2.2. The bug was fixed in version 3.2.3. The tutorial is unfortunately based on the older version with the bug. See also #46; the error there is that the tutorial is based on an incorrect older version of MrBayes.
