### ISSUE TITLE
Dollo in MrBayes

### ISSUE THREAD

**Issue by Alexei-Kassian** [NBISweden/MrBayes#102]
Dear all,
is the Stochastic Dollo model implemented in MrBayes? I failed to find it in the manual/help. AFAIK, StDollo is available in the BEAST package (as described by Bouckaert & Robbeets https://www.biorxiv.org/content/10.1101/207571v1), but what about MrBayes.
Best,
Alexei

**Comment by nylander** [comment]
Dear Alexei,
the short answer answer is "No".
