### ISSUE TITLE
Incorporate old models from Seraina

### ISSUE THREAD

**Issue by andkaha** [NBISweden/MrBayes#108]
Seraina's code is located on the `features/Seraina` branch, in `src/Seraina`.

GitHub link to that branch and directory: https://github.com/NBISweden/MrBayes/tree/feature/Seraina/src/Seraina

**Comment by andkaha** [comment]
Status update:

Done with Seraina's `mb.h`, `bayes.c` and `command.c`.  The code does not seem to be too invasive. There was a question in a comment in the code in `command.c`:

```
                t->isClock = YES;   /* assume clock if rooted */ //SK: remove this in case I want to read in user trees for directional model! Does that break anything else?
```

**Comment by ronquist** [comment]
This issue should be addressed by the incorporation of the Seraina branch in the develop branch. Will close this issue now.

/Fredrik
