### ISSUE TITLE
Alignments longer than 100K

### ISSUE THREAD

**Issue by pnatsi** [NBISweden/MrBayes#109]
### What is the issue that you are having?

I have a nexus alignment longer than 100K sites and MrBayes is not accepting it

MrBayes > exec mattia92_I35.nexus
```
   Executing file "mattia92_I35.nexus"
   UNIX line termination
   Longest line length = 140562
   Parsing file
   Expecting NEXUS formatted file
   Reading data block
      Allocated taxon set
      Allocated matrix
      Defining new matrix with 90 taxa and 140518 characters
      Data is Restriction
      Data matrix is not interleaved
      Gaps coded as -
      Missing data coded as ?
      Taxon  1 -> Acanthocheilonema_viteae_protein
      Error while parsing a string. Token "11111111111111100011...[followed by at least 99970  more charectors]" is too long.
      Maximum allowed length of a token is 99990
      The error occurred when reading char. 100015-100034 on line 10
         in the file 'mattia92_I35.nexus'

   Returning execution to command line ...

   Error in command "Execute"
```

### What is the environment that you run MrBayes in?
  - Operating system (including variant and release):
  - Version of MrBayes: 3.2.7
  - If possible, include the output of the `Version` command in MrBayes below:
```
   MrBayes 3.2.7a

   Features:  SSE readline
   Host type: x86_64-unknown-linux-gnu (CPU: x86_64)
   Compiler:  gnu 4.4.7
```

**Comment by nylander** [comment]
Dear pnatsi,

thank you for your report. We will look in to this issue.

Meanwhile, we can clarify that it is not the "alignment length" (i.e. length of the sequences) that is the limitation when reading your file, but the length of any string ("token") that the program is reading into memory.

You will (most probably) be able to read your file if you change the input format to "interleaved". Just make sure that each sequence length is shorter than the "token limit" reported by MrBayes.

Yours
Johan

Example of an "interleaved" data block in nexus format:

```
\#NEXUS
begin data;
  dimensions ntax=3 nchar=10;
  format missing=? gap=- datatype=dna interleave;
  matrix

    apa AAAAA
    bpa AAAAA
    cpa AAAAA

    apa AAAAA
    bpa AAAAA
    cpa AAAAA
  ;
end;
```

**Comment by nylander** [comment]
Closing this and refering to #113
