### ISSUE TITLE
Bug in likelihood calculations for mixed aa model and partitioned data

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#112]
- Last modified: tor jun 20, 2019  01:38
- Sign: JN

## Bug description

Likelihood calculations fail with partitioned protein data,
in combination with `prset aamodelpr=mixed`, unless unlinking
of `aamodel` is made.

Using a fixed aa model (e.g. `prset aamodelpr=fixed(poisson)` works,
with or without unlinking the `aamodel`.

This bug is also present in my binaries at least back to v.3.2.1,
where we get additional warnings:
`WARNING: In LIKE_EPSILON - for division 1 char 0 has like = 0.000000000000000000000000000000`

## Tests to reproduce

MrBayes version:

```
$ mb -v
MrBayes, Bayesian Analysis of Phylogeny

Version:   3.2.7a
Features:  SSE AVX Beagle readline
Host type: x86_64-unknown-linux-gnu (CPU: x86_64)
Compiler:  gnu 7.4.0

```

### Mixed, partitions, and with BEAGLE

    exe avian_ovomucoids.nex
    set autoclose=yes nowarn=yes
    charset first = 1-44
    charset second = 45-88
    partition part = 2: first, second
    set partition = part
    lset applyto=(all) rates=invgamma
    prset applyto=(all) ratepr=variable aamodelpr=mixed
    unlink statefreq=(all) revmat=(all) shape=(all) pinvar=(all)
    mcmc nruns=1 nchains=1 ngen=1000 printfreq=10 samplefreq=10
    quit

##### Comments

- This will yield log likelihoods with value `-inf`.
- p file: No MCMC updates are done (same values in the last iteration as the start. For all columns.)
- t file: No MCMC updates are done (same tree in the last iteration as the start.)

### Mixed, partitions, without BEAGLE

    exe avian_ovomucoids.nex
    set autoclose=yes nowarn=yes
    set usebeagle=no
    charset first = 1-44
    charset second = 45-88
    partition part = 2: first, second
    set partition = part
    lset applyto=(all) rates=invgamma
    prset applyto=(all) ratepr=variable aamodelpr=mixed
    unlink statefreq=(all) revmat=(all) shape=(all) pinvar=(all)
    mcmc nruns=1 nchains=1 ngen=1000 printfreq=10 samplefreq=10
    quit

##### Comments

- This will yield log likelihoods with > 300 digits!
- p file: No MCMC updates are done (same values in the last iteration as the start. For all columns.)
- t file: No MCMC updates are done (same tree in the last iteration as the start.)

### Mixed, partitions, with BEAGLE, and unlinkning aamodel

    exe avian_ovomucoids.nex
    set autoclose=yes nowarn=yes
    charset first = 1-44
    charset second = 45-88
    partition part = 2: first, second
    set partition = part
    lset applyto=(all) rates=invgamma
    prset applyto=(all) ratepr=variable aamodelpr=mixed
    unlink statefreq=(all) revmat=(all) shape=(all) pinvar=(all) aamodel=(all)
    mcmc nruns=1 nchains=1 ngen=1000 printfreq=10 samplefreq=10
    quit

##### Comments

- Starts the MCMC, but run may stall (fail) after some time!

**Comment by nylander** [comment]
See also issue #110

**Comment by ronquist** [comment]
The problem here is that MrBayes does not deal properly with the inherit conflict when the model settings says that the aamodel should be linked, and the state frequencies (which are taken from the aamodel) are unlinked. Now the aamodel is unlinked if any of these two parameters are unlinked, which is in line with the logic used in other such cases.
