### ISSUE TITLE
Excessive warnings for coalescent model

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#117]
Trying to run `mcmc` with the coalescence model results in a warning message:

>  WARNING: You are using a coalescent model but the clock rate is fixed to 1.0.
>      This is likely to be incorrect unless you have set the population size prior
>      ('prset popsizepr') to reflect an appropriate prior on theta. 
>   Do you want to continue with the run regardless? (yes/no):

Answering 'yes' to the question ends up in asking again (30 times, one for each partition).

Running with `set autoclose=yes nowarnings=yes` still gives the warning (31 times).

In this example, the user **did** explicitly set the `popsizepr` prior to some value,
so why the warning?

#### Offending code (`model.c`)

```C
/* check coalescence model */
for (i=0; i<numTrees; i++)
    {
    t = GetTreeFromIndex(i, 0, 0);
    if ((!strcmp(modelParams[t->relParts[0]].clockPr,"Coalescence") || !strcmp(modelParams[t->relParts[0]].clockPr,"Speciestreecoalescence"))
        && !strcmp(modelParams[t->relParts[0]].clockRatePr, "Fixed") && AreDoublesEqual(modelParams[t->relParts[0]].clockRateFix, 1.0, 1E-6) == YES)
        {
        MrBayesPrint("%s   WARNING: You are using a coalescent model but the clock rate is fixed to 1.0.\n", spacer);
        MrBayesPrint("%s      This is likely to be incorrect unless you have set the population size prior\n", spacer);
        MrBayesPrint("%s      ('prset popsizepr') to reflect an appropriate prior on theta. \n", spacer);

        if (noWarn == NO)
            {
            answer = WantTo("Do you want to continue with the run regardless");
            if (answer == YES)
                {
                MrBayesPrint("%s   Continuing with the run...\n\n", spacer);
                }
            else
                {
                MrBayesPrint("%s   Stopping the run...\n\n", spacer);
                return (ERROR);
                }
            }
        }
    }

```

The default setting for the `Clockratepr` is `Fixed(1.00)`, and this is what the code picks up.
So unless we change it before running `mcmc`, this warning will always appear.

The test should do "if Clockratepr is Fixed(1.00); issue a warning, unless prset popsizepr is set".

On the other hand, there is already a default prior set on popsizepr!
So why the warning? What am I missing?  

#### Commands to repeat

```
$ wget https://raw.githubusercontent.com/NBISweden/MrBayes/develop/examples/finch.nex
$ sed -i 165d finch.nex
$ mb -i finch.nex
mcmc ngen=100000 nchains=1
```

#### MrBayes version

3.2.7a (branch develop, 2019-July-24)

```
$ mb -v
MrBayes, Bayesian Analysis of Phylogeny

Version:   3.2.7a
Features:  SSE AVX Beagle readline
Host type: x86_64-unknown-linux-gnu (CPU: x86_64)
Compiler:  gnu 7.4.0
```

**Comment by ronquist** [comment]
Solved in feature/issue_117. The warning is appropriate but it is only printed once now.
