### ISSUE TITLE
Exceeding max user trees results in core dump

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#118]
## Description

Reading too many user trees results in a core dump on Linux.

The (old) manual says "you can read up to 100 trees". In my test, however, I manage to read at least 200, but above that the program crashes (core dump).

Would be better if the number of read user trees (or the memory requirements) was monitored,
and handled appropriately.

## Commands to reproduce

    set autoclose=yes nowarnings=yes
    execute primates.nex
    mcmc nruns=1 ngen=202 samplefreq=1
    execute primates.nex.t

## MrBayes version

    MrBayes, Bayesian Analysis of Phylogeny

    Version:   3.2.7a
    Features:  SSE AVX Beagle readline
    Host type: x86_64-unknown-linux-gnu (CPU: x86_64)
    Compiler:  gnu 7.4.0

**Comment by andkaha** [comment]
Can't reproduce this with
```
   MrBayes 3.2.7a

   Features:  SSE AVX Beagle readline
   Host type: x86_64-unknown-openbsd6.6 (CPU: x86_64)
   Compiler:  clang 8.0.0
```

**Comment by andkaha** [comment]
Compiling with GCC gives the same behaviour though. Will look at core-files...

**Comment by andkaha** [comment]
This is Beagle-related. Does not dump core when running without using the Beagle library.

**Comment by nylander** [comment]
You are right, works on my side too when building with `./configure --without-beagle ; make`

```
Version:   3.2.7a
Features:  SSE AVX readline
Host type: x86_64-unknown-linux-gnu (CPU: x86_64)
Compiler:  gnu 7.4.0
```

Interestingly, I found yet another bug! After running the example above in an interactive session, typing the short command `q` and hit Enter, I get a core dump! Repeating the same thing but typing `quit`, that's OK!

To make it more interesting, running the example above, except the last line (`execute primates.nex.t`), then it works with both `q` or `quit`.

My guess is that this, still, has to do with how the memory is allocated/freed for the user trees read into memory, and how the memory is treated when quitting. But the `q` versus `quit`? I have no clue.

**Comment by nylander** [comment]
To continue the buggy behavior: trying to find the limit of number of user trees actually read by the program,
```
set autoclose=yes nowarnings=yes
execute primates.nex
mcmc nruns=1 ngen=500 samplefreq=1
execute primates.nex.t
```
typing `q` or `quit` doesn't quit the program (nothing happens but to return the prompt).

Regarding the number of trees read, the last progress printing reads
```
      Successfully read tree 'gen.203'
      Reached end of file
```
But again, no more commands can be executed.

And, in addition, I cannot seem to repeat the the `q` versus `quit` behavior described previously (when running 202 generations): both now results in a core dump. Strange things are happening...

**Comment by andkaha** [comment]
Ok, so I deleted the "beagle-related" tag from this issue as it may well be something up with our code. I'm seeing what you're seeing and in a debugger I can see that the segfault is caused by trying to use `strcmp()` on a pointer that is `NULL`. I'm guessing there is a buffer that gets overrun by the trees. I will try to track it down somehow.

**Comment by andkaha** [comment]
Could you try again with a segfaulting configuration with the most recent commits incorporated, and also test with `--without-readline` please?

**Comment by andkaha** [comment]
PR #151 enforces the hard upper boundary of 200 initial trees.

Pending: Changes to manual.

**Comment by nylander** [comment]
Current version of the documentation does not conflict with the current max tree settings (no changes in the manual needed). Closing.
