### ISSUE TITLE
Problems with new configure

### ISSUE THREAD

**Issue by ronquist** [NBISweden/MrBayes#12]
I see that the new configure file is quite different from the old one. The changes are good for the most part, I am sure. I certainly appreciate the better and more elegantly formatted help info, among other things. However, I found two issues:

1. The Beagle test files on my system. The old configure.in detected my beagle installation correctly and compiled the beagle version with no problem.
2. The debug option is gone. Is there a reason for this? I used it often.

**Comment by ronquist** [comment]
This is on the develop branch, I guess I should add. The feature/fixup_master branch does not have this issue.

**Comment by kusalananda** [comment]
1.  Does `configure` not pick up Beagle? Do you have `pkgconf` installed? Do we want to have a dependency on `pkgconf`? If not, I will change the Beagle detection in `configure.ac`, but it will be a bit messier.
2. No reason for dropping the debug option. I will put it back in. The default set of flags used currently is `-g -O2 -Wall` which adds debugging symbols (this is the default with GNU autotools). I'll make the default `-O3 -Wall` instead. With `--enable-debug` I'll set the flags to `-O2 -g -Wall` (`-g` is portable, and `-O2` should not optimize away code to make debugging with `gdb` difficult).

**Comment by kusalananda** [comment]
The reason feature/fixup_master works is that it's basically a straight import of the Sourceforge repository.

**Comment by ronquist** [comment]
I do not have pkgconf so that explains it. I am not sure whether it is a good idea to rely on pkgconf. If so, we need to at least check when it is not installed and then print an error message if it is not.
I trust you on the flags.

**Comment by ronquist** [comment]
If -03 is faster, we should have that as the default even though it is not compatible with -g. I think.

**Comment by kusalananda** [comment]
Would it be acceptable to error out of `configure` if `pkgconf` is not found? Or are you saying we simply should not use it? I'm _for_ using `pkgconf`. It's commonly used for exactly what we're using it for here.

**Comment by ronquist** [comment]
So i now have pkg-config and the error is still there:
```
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for BEAGLE... no
configure: error: --with-beagle was given, but test for Beagle failed
```

**Comment by ronquist** [comment]
It IS pkg-config right, and not pkgconf? Homebrew redirects pkgconf to pkgconfig, which gives the script pkg-config.

**Comment by kusalananda** [comment]
Is Beagle installed under `/usr/local`?  Set `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig`.

**Comment by kusalananda** [comment]
`pkg-config`, `pkgconf` and `pkgconfig` is all the same. There are a couple of different implementations, but the functionality is the same.

**Comment by kusalananda** [comment]
Basically, you need to set `PKG_CONFIG_PATH` to point to the directory containing the file `hmsbeagle-1.pc`.

One idea would be to let `--with-beagle` take an argument, which would override `pkgconfig`.  The argument would be the _prefix path_ that Beagle was installed under, i.e `/usr/local` or `$HOME/local`, `/opt` or whatever.

**Comment by ronquist** [comment]
No file called hmsbeagle-1.pc installed on my computer. I reran the most recent version of the Mac installer to make sure I was not missing something. Isn't this a Windows-specific file? I have a very old version of this file in my Windows partition.

**Comment by ronquist** [comment]
Do you have access to a Mac system for testing?

**Comment by kusalananda** [comment]
When a clone the Beagle repository, run `configure` and `make && make install`, it installs this file under `lib/`. Is there another way to install Beagle?

I'm on a Mac, yes, but I work from the command line.

**Comment by ronquist** [comment]
Maybe it is their Mac binary executable installer that does not install this file.

**Comment by kusalananda** [comment]
Hmm... I just ran that installer, and it wrote library files into `/usr/local`.  Does it put any headers or anything else anywhere?  I think this might be just for running things already compiled with Beagle, not to develop against...

Seriously, where does it put the header files? You have them, right?

**Comment by ronquist** [comment]
This is what I have after running the installer. Anywhere else I should be looking?
```
/usr/local/lib/libhmsbeagle-1.0.1.dylib		/usr/local/lib/libhmsbeagle-cpu.21.so		/usr/local/lib/libhmsbeagle-jni.jnilib
/usr/local/lib/libhmsbeagle-cpu-1.0.1.dylib	/usr/local/lib/libhmsbeagle-cpu.a		/usr/local/lib/libhmsbeagle-opencl.21.so
/usr/local/lib/libhmsbeagle-cpu-sse-1.0.1.dylib	/usr/local/lib/libhmsbeagle-cuda-1.0.1.dylib	/usr/local/lib/libhmsbeagle.1.dylib
/usr/local/lib/libhmsbeagle-cpu-sse.1.dylib	/usr/local/lib/libhmsbeagle-cuda.1.dylib	/usr/local/lib/libhmsbeagle.a
/usr/local/lib/libhmsbeagle-cpu-sse.21.so	/usr/local/lib/libhmsbeagle-cuda.21.so		/usr/local/lib/libhmsbeagle.dylib
/usr/local/lib/libhmsbeagle-cpu-sse.a		/usr/local/lib/libhmsbeagle-cuda.a
/usr/local/lib/libhmsbeagle-cpu.1.dylib		/usr/local/lib/libhmsbeagle-jni.a
```

**Comment by ronquist** [comment]
And also
```
/usr/local/include/libhmsbeagle-1:
libhmsbeagle

/usr/local/include/libhmsbeagle-1.0:
libhmsbeagle

```

**Comment by kusalananda** [comment]
After running the installer, I only have `/usr/local/lib`. That's all. I never touch `/usr/local` ordinarily, so there's nothing else there. 

It's getting late. I will sleep. Tomorrow I will start sorting out `configure.ac` and the debug flag (and the utils feature branch). I will get back to this later.

**Comment by ronquist** [comment]
OK. Installing beagle from source is not something we want regular users to go through. It is autogen and not autoconf. The install instructions are out-of-date. I am getting a clang error, which may be because they are using some very recently added clang option in their Makefile. Etc. Painful even for someone who is fairly experienced. The beagle repo strongly recommends that you run the binary installer, so we need to make mrbayes work with whatever it installs. Here you have an ls -l listing of my /usr/local/lib files that start with libhms (the /usr/local/include files may be old and not installed now by the installer; I have had numerous versions of beagle installed on my machine).

```
-rwxr-xr-x@ 1 ronquist  wheel    42824  5 Okt  2010 /usr/local/lib/libhmsbeagle-1.0.1.dylib
-rwxr-xr-x@ 1 ronquist  wheel   135264  5 Okt  2010 /usr/local/lib/libhmsbeagle-cpu-1.0.1.dylib
-rwxr-xr-x@ 1 ronquist  wheel    92816  5 Okt  2010 /usr/local/lib/libhmsbeagle-cpu-sse-1.0.1.dylib
-rwxr-xr-x@ 1 root      wheel   128904 18 Jun  2011 /usr/local/lib/libhmsbeagle-cpu-sse.1.dylib
-rwxr-xr-x  1 root      admin   137308 10 Feb  2014 /usr/local/lib/libhmsbeagle-cpu-sse.21.so
-rw-r--r--@ 1 ronquist  wheel   103296  5 Okt  2010 /usr/local/lib/libhmsbeagle-cpu-sse.a
-rwxr-xr-x@ 1 root      wheel   122728 18 Jun  2011 /usr/local/lib/libhmsbeagle-cpu.1.dylib
-rwxr-xr-x  1 root      admin   144264 10 Feb  2014 /usr/local/lib/libhmsbeagle-cpu.21.so
-rw-r--r--@ 1 ronquist  wheel   150120  5 Okt  2010 /usr/local/lib/libhmsbeagle-cpu.a
-rwxr-xr-x@ 1 ronquist  wheel  5348928  5 Okt  2010 /usr/local/lib/libhmsbeagle-cuda-1.0.1.dylib
-rwxr-xr-x@ 1 root      wheel  5358732 18 Jun  2011 /usr/local/lib/libhmsbeagle-cuda.1.dylib
-rwxr-xr-x  1 root      admin  5396844 10 Feb  2014 /usr/local/lib/libhmsbeagle-cuda.21.so
-rw-r--r--@ 1 ronquist  wheel  5379800  5 Okt  2010 /usr/local/lib/libhmsbeagle-cuda.a
-rw-r--r--@ 1 ronquist  wheel    65856  5 Okt  2010 /usr/local/lib/libhmsbeagle-jni.a
-rwxr-xr-x  1 root      admin    21824 10 Feb  2014 /usr/local/lib/libhmsbeagle-jni.jnilib
-rwxr-xr-x  1 root      admin  1945508 10 Feb  2014 /usr/local/lib/libhmsbeagle-opencl.21.so
-rwxr-xr-x  1 root      admin    45060 10 Feb  2014 /usr/local/lib/libhmsbeagle.1.dylib
-rw-r--r--@ 1 ronquist  wheel    49560  5 Okt  2010 /usr/local/lib/libhmsbeagle.a
lrwxr-xr-x  1 ronquist  wheel       20 13 Jul 23:33 /usr/local/lib/libhmsbeagle.dylib -> libhmsbeagle.1.dylib

```

**Comment by ronquist** [comment]
The old configure.in has a test for beagle and my machine passes that test. Maybe that could be useful.

**Comment by kusalananda** [comment]
The binary Beagle installer does not install header files.  I have verified this by looking at the package specification left behind by the installer (using Apple's `pkgutil`). Beagle installed from it can not be used to build a working MrBayes.

**Comment by ronquist** [comment]
So how can I compile a working beagle version of mrbayes then with the old configure.in-generated makefile?

**Comment by ronquist** [comment]
Maybe a few hours of sleep will help...

**Comment by kusalananda** [comment]
You mentioned that you've had numerous versions of Beagle installed. Could it be that you're seeing header files put in place by an older installation?

I have now _unpacked_ the `BEAGLE-1.21.pkg` file that constitutes the installer. There are no header files there, only shared libraries (going into `/usr/local/lib`), and one file which is being put into `/Library/Java/Extensions`.

Yes, sleep will halp.  And a sandwich.

**Comment by kusalananda** [comment]
Fredrik,

I have added `--enable-debug` to `configure`. 

_Without_ `--enable-debug`, or _with_ `--disable-debug`:

- `CFLAGS` is set to `-O3`.
- `-std=c99 -pedantic` is tagged onto the end.
- `-Wall` is added by a portable macro that knows about different compilers.
- `-DNDEBUG` should be added (I forgot it, will fix it ASAP).

_With_ `--enable-debug`:

- `CFLAGS` is set to `-g -O2`.
- `-std=c99 -pedantic` is added as before.
- `-Wall` is added as before.

Furthermore, the `--with-beagle` option to `configure` has gained new capabilities.

Using `--with-beagle` will

- Try to find the Beagle headers and libraries in `/usr/local`.
- Failing that, fall back on `pkg-config`.

Using something like `--with-beagle=$HOME/local` will

- Try to find the Beagle headers and libraries in `$HOME/local`.
- Failing that, fall back on the default behaviour (looking in `/usr/local` etc. as above).

Not using `--with-beagle` will act as if using `--with-beagle` without a path argument (checking `/usr/local`, then with `pkg-config`), but _won't be fatal if Beagle can't be found_.

**Comment by ronquist** [comment]
Sounds reasonable.

I still need to figure out why the new configure file does not work with beagle on my machine.

I am using clang that comes with XCode.
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```
beagle-lib does not compile according to instructions on my machine because of non-supported option `-dumpspecs`:
```
Fredriks-MacBook-Pro:beagle-lib ronquist$ make
Making all in libhmsbeagle
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in GPU
Making all in kernels
echo "// auto-generated header file with CUDA kernels PTX code" > BeagleCUDA_kernels.h
/usr/local/cuda/bin/nvcc -o BeagleCUDA_kernels.ptx -ptx -DCUDA -DSTATE_COUNT=4 \
		./kernels4.cu -O3 -m64 -D_POSIX_C_SOURCE -ccbin /usr/bin/clang -DHAVE_CONFIG_H -I/Users/ronquist/dev/beagle-lib -I/Users/ronquist/dev/beagle-lib
clang: error: unsupported option '-dumpspecs'
clang: error: no input files
make[4]: *** [BeagleCUDA_kernels.h] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```
It seems that `-dumpspecs` is a gcc option, so I may have to switch compiler, which will take me a while to figure out.

I will have to do some more detective work to find out what the binary Mac OS beagle installer actually puts on my machine.

I do get a compile warning without the beagleGetVersion declaration. So that needs to be solved, I guess.

I would like to keep the mrbayes compiles clean with -Wall, we have basically managed to keep it that way through the years with some exceptions now and then, across several different compilers. However, if I now turn on all XCode warnings (clang), I  get more than 500 warnings. Mostly they seem to be inconsequential or even just distractive but it is annoying anyway. I will deal with them when I have time.

C99 is fine for MrBayes, it does not have to be C11. We have been quite conservative in adopting new standards and new technologies and it usually simplifies life and increases portability. There is a reason why HPC people still prefer Fortran, I guess...

I will try to write a short coding style document for you and for other contributors. Note the weird placement of curly braces in MrBayes. It is fairly consistent throughout the code, so we should keep it that way. It is John's fault originally, and now I have spent 15 years struggling with this style in MrBayes even though I program in a slightly different style elsewhere. Both John and I are meticulous with spacing, it does help to find things quickly if you line things up nicely. We have no doxygen documentation of the code but it might be worth considering adding such comments if you end up doing a fair amount of work on the code.

We still miss a large number of files from the SourceForge repo. The test folder is extremely important, it has a number of test files that are crucial in checking that the program behaves properly. At some point we may want to set up automated tests based on some of these files. I also think there might be some additional documentation files that should be transferred to the SourceForge repo, and lots of extra examples files that are useful for testing purposes.

Finally there is the issues on SourceForge and the e-mail list...

When the configure stuff is working with beagle for me, we may want to put a release together, to see if we can figure out how to do this on github. I would like to have the SourceForge move to github completed by then, if possible, though. If you want to push the beagle fix to master before then it is fine by me. It probably makes sense.

**Comment by kusalananda** [comment]
I hear you.

I run all my code though `clang-format`, which is fairly configurable.  I will try to make it adhere to the coding style that is already in place.

I will sort out the test files. I will open an issue for that. Likewise I will open issues for the bug tracking and emailing list.

The binary Beagle installer puts these files on the target host:

In `/usr/local/lib`:
```
libhmsbeagle-cpu-sse.21.so
libhmsbeagle-cpu.21.so
libhmsbeagle-cuda.21.so
libhmsbeagle-jni.jnilib
libhmsbeagle-opencl.21.so
libhmsbeagle.1.dylib
libhmsbeagle.dylib
```

In `/Library/Java/Extensions`:
```
libhmsbeagle-jni.jnilib
```


Can we close this particular issue though?

**Comment by ronquist** [comment]
Is there no way to make MrBayes compile with beagle, when beagle is installed with the binary installer then?

**Comment by ronquist** [comment]
If so, we need to document this properly in the compile instructions. We should also have the configure script check whether the user might have used the binary installer and then print an appropriate message that you need to install the beagle library by compiling from source.

**Comment by ronquist** [comment]
Otherwise, the configure script now makes perfect sense. Forgot to say that.

**Comment by kusalananda** [comment]
I'm closing this issue for the moment.

I'll just add that I've enabled the Wiki and have started to write a "style guide": https://github.com/NBISweden/MrBayes/wiki/MrBayes-source-code-style-guide
