### ISSUE TITLE
Releases 3.2.5 and 3.2.6: incorrectly packaged (tar.gz and zip)

### ISSUE THREAD

**Issue by tardigradus** [NBISweden/MrBayes#124]
The tar.gz and zip packages for versions 3.2.5 and 3.2.6 don't contain the correct files:

    $ for f in MrBayes-3.2.[56]*tar.gz; do tar -tzf $f; done   
    MrBayes-3.2.5/
    MrBayes-3.2.5/MrBayes-3.2.5_MACx64.pkg
    MrBayes-3.2.6/
    $ for f in MrBayes-3.2.[56]*zip; do unzip -l $f; done
    Archive:  MrBayes-3.2.5.zip
    aa55a2df39a987593ab31f0320c7342bf10939bb
      Length      Date    Time    Name
    ---------  ---------- -----   ----
            0  2015-05-28 17:01   MrBayes-3.2.5/
      8293177  2015-05-28 17:01   MrBayes-3.2.5/MrBayes-3.2.5_MACx64.pkg
    ---------                     -------
      8293177                     2 files
    Archive:  MrBayes-3.2.6.zip
    f986baef53357a3331c3881b7a91dff5d7f60907
      Length      Date    Time    Name
    ---------  ---------- -----   ----
            0  2015-11-25 15:33   MrBayes-3.2.6/
    ---------                     -------
            0                     1 file

I realize that this has been addressed in #71.  However, I think the broken
packages should either be removed or fixed.  In the interest of reproducibility
of previous results, I would prefer the latter.

**Comment by andkaha** [comment]
We recently made a cleanup of files that should never had been added to the Git repository. This includes the `zip` and `tar` archives of previous releases.  We did this to slim the repository down by _a large amount_.

What we obviously did _not_ do is to move the release tags to the correct commits, which means that the Git hub releases currently point to seemingly empty repositories.

Thank you for noticing this. We will try to amend the issue as soon as possible (during the current week).

**Comment by andkaha** [comment]
What I'll do is that I'll try to upload the removed archives to the Github releases page at https://github.com/NBISweden/MrBayes/releases as separate assets today. Later, I'll move the tags so that the auto-rolled archives hopefully sorts themselves out.

**Comment by andkaha** [comment]
Ok, so now the v3.2.5 release is available at
https://github.com/NBISweden/MrBayes/releases/download/v3.2.5/mrbayes-3.2.5.tar.gz

Likewise, the v3.2.6 release is available at
https://github.com/NBISweden/MrBayes/releases/download/v3.2.6/mrbayes-3.2.6.tar.gz

**Comment by tardigradus** [comment]
Great, thanks for responding so rapidly.  I have successfully built 3.2.5 for a user, who was experiencing a segmentation fault with 3.2.6 (but that is a different story).

Would it be also possible to provide 3.2.7 at 

    https://github.com/NBISweden/MrBayes/releases/download/v3.2.7/mrbayes-3.2.7.tar.gz

too?  It makes it easier for automated build software if the paths to the sources are all the same, modulo the version.

**Comment by andkaha** [comment]
Yes, this makes sense. I will upload the `tar` archives for v3.2.7 and v3.2.7a as well (a bit later this evening; I'm at home doing non-work stuff at the moment).

If you could open a new issue about that segmentation fault, that would be appreciated. Including a reproducible example and the exact configuration used would be even more helpful.

**Comment by andkaha** [comment]
Todo: Move tags (sigh)

**Comment by tardigradus** [comment]
I'm still waiting for a user to provide a minimal working example which demonstrates the segfault.  I'll get back to you when I have it.  Currently all I can say is that MrBayes 3.2.5 built with the combination

    GCC/6.4.0-2.28
    OpenMPI/2.1.2

works, but it doesn't if built with

    GCC/7.3.0-2.30
    OpenMPI/3.1.1

**Comment by andkaha** [comment]
Now fixed, I believe.
