### ISSUE TITLE
mcmc: LogPrior() function may use garbage values to increment lnPrior value

### ISSUE THREAD

**Issue by andkaha** [NBISweden/MrBayes#127]
In the function `LogPrior()` in `mcmc.c`, there is a `MrBflt` variable called `x`.

If `p->paramType` is `BRLENS_CLOCK_BD` or `BRLENS_CLOCK_FOSSIL60`, then this uninitialised `x` may be used to increment `lnPrior`.

**Comment by ronquist** [comment]
This is not a bug as x is initialized appropriately where needed, in the cases referred to above in separate function calls. To avoid the compiler warning, I initialized x in LogPrior to 0.0. I also added comments where the initialization of x is less obvious (the cases referred to above). I created a pull request for the fix, which is in branch feature/issue-127 (an overkill perhaps...).
