### ISSUE TITLE
Covarion model and restriction data

### ISSUE THREAD

**Issue by PhyloStar** [NBISweden/MrBayes#131]
Hi. Does MrBayes respect the setting of the covarion model to yes when the data is restriction type? I ran the analysis with a unrooted tree prior. The log file does not show any parameter sampling for covarion model. Am I right to say that for restriction site data type, the only valid  substitution model is F81 model?

-Taraka

**Comment by ronquist** [comment]
Hi! The covarion model setting only applies to nucleotide (4by4) and amino acid models in MrBayes at this point, although there is no problem to implement a covarion model for binary data if one wished to do so. Currently, for restriction sites, you can use the F81 model or the JC model. Note that the restriction site data type also allows correction for ascertainment bias.
