### ISSUE TITLE
any method to reduce solution space for MRBAYES?

### ISSUE THREAD

**Issue by KHBHH** [NBISweden/MrBayes#134]
Hi,

I would like to ask if there is any method or tool to reduce the solution space for MSBAYES? 

Thanks!

**Comment by nylander** [comment]
Not entirely sure what is meant with "solution space" in this context. If somewhat similar to "search space", or "How the MCMC is exploring parameter space", then you may of course set different MCMC- proposals, tunings, and start points in MrBayes. All that then potentially limits the "solution space".
/Johan
