### ISSUE TITLE
Failure in searching header files beagle.h and platform.h when building MrBayes supporting Beagle

### ISSUE THREAD

**Issue by wanyuac** [NBISweden/MrBayes#136]
Environment:  
- Ubuntu 18.04.3
- MrBayes 3.2.7a, Beagle-lib 3.1.2, MPIHC-3.3.1  

Beagle installation directory:  
```
/usr/local/lib/beagle/
 |------- lib/
 |         +--------- library files
 |         +--------- pkgconfig
 |                        +---------- hmsbeagle-1.pc
 +------- include/
 |          +--------- libhmsbeagle-1/
 |                        +--------- libhmsbeagle/
 |                                     +--------- beagle.h
 |                                     +--------- platform.h  
```

### Installation procedure reproducing the error:  
```bash
git clone --depth=1 https://github.com/NBISweden/MrBayes.git
cd MrBayes

env MPICC="/usr/local/bin/mpicc" PKG_CONFIG_PATH="/usr/local/lib/beagle/lib/pkgconfig" BEAGLE_CFLAGS="-I/usr/local/lib/beagle/lib/pkgconfig/hmsbeagle-1" BEAGLE_LIBS="-L/usr/local/lib/beagle/lib -Wl,-rpath=/usr/local/lib/beagle/lib -lhmsbeagle" ./configure --with-mpi

make -j2
sudo make install
```

Note that I could reproduce the error when Beagle was installed to its default location (/usr/local/lib), although the installation procedure demonstrated in this Issue refers to a non-default location (/usr/local/lib/beagle/lib/).

### Error messages
```bash
/usr/bin/ld: cannot find -lhmsbeagle
collect2: error: ld returned 1 exit status
Makefile:402: recipe for target 'mb' failed
make[2]: *** [mb] Error 1
make[2]: Leaving directory '/home/user1/Downloads/MrBayes/src'
Makefile:310: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/user1/Downloads/MrBayes/src'
Makefile:418: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
As a result, I could not build MrBayes due to this error.

### Suspected causes
- Command ```#include "libhmsbeagle/beagle.h"``` in  MrBayes/src/bayes.h could not find beagle.h.
- Command ```#include "libhmsbeagle/platform.h"``` in beagle.h failed.

### Solution
Creating a sub-directory libhmsbeagle under the MrBayes/src and making two symbolic links make the buiding process successful:

```bash
cd MrBayes
ln -s /usr/local/lib/beagle/include/libhmsbeagle-1/libhmsbeagle/beagle.h ./src/libhmsbeagle/beagle.h
ln -s /usr/local/lib/beagle/include/libhmsbeagle-1/libhmsbeagle/platform.h ./src/libhmsbeagle/platform.h
make -j2
sudo make install
```

**Comment by andkaha** [comment]
The `BEAGLE_CFLAGS` variable seems to contain the wrong path for the headers of the Beagle library.  You currently use
```
BEAGLE_CFLAGS="-I/usr/local/lib/beagle/lib/pkgconfig/hmsbeagle-1"
```
which is the path to the directory containing the file that `pkg-config` would have used to give you the correct include paths etc. for Beagle.

If you want to set an explicit include path for the Beagle library, it looks as if you'd want to use
```
BEAGLE_CFLAGS="-I/usr/local/lib/include/libhmsbeagle-1"
```

A better option would be to leave the `BEAGLE_CFLAGS` and `BEAGLE_LIBS` options untouched and let `pkg-config` use the data stored in `hmsbeagle-1.pc` to set the correct values.

**Comment by wanyuac** [comment]
Thank you @kusalananda for explaining the meaning of ```BEAGLE_CFLAGS``` and correcting my command. I eventually managed to build MrBayes (MPI + Beagle) using the following command:

```
env MPICC="/usr/local/bin/mpicc" PKG_CONFIG_PATH="/usr/local/lib/beagle/lib/pkgconfig" BEAGLE_CFLAGS="-I/usr/local/lib/beagle/include/libhmsbeagle-1" BEAGLE_LIBS="-L/usr/local/lib/beagle/lib -Wl,-rpath=/usr/local/lib/beagle/lib -lhmsbeagle" ./configure --with-mpi
```
