### ISSUE TITLE
Windows Beagle executable

### ISSUE THREAD

**Issue by Avatar4eg** [NBISweden/MrBayes#139]
Is there are any instruction to compile MrBayes for Windows with Beagle 3?
Or maybe 3.2.7 version with Beagle.

**Comment by nylander** [comment]
Hi @Avatar4eg,
no, we have not provided any compile instructions for the MrBayes-code on Windows. One may, however, use the same (in principle) build system on Windows as one does on Linux or MacOS by using something like "Windows Subsystem for Linux", "CygWIN", "MinGW", or similar.
/Johan
