### ISSUE TITLE
How branch lengths are updated when the topology is changed?

### ISSUE THREAD

**Issue by computingmachine** [NBISweden/MrBayes#148]
I am using MrBayes to estimate a tree but I am suspecting how the tree branch lengths are estimated.  If the tree on the left is current tree but tree on the right is proposal tree, the positions of t3 and t5 are exchanged. How will the branch lengths change? 

![eg](https://user-images.githubusercontent.com/35937090/72492299-a9457d80-37ea-11ea-9e87-dbc642cfbd8f.png)

**Comment by nylander** [comment]
Dear @computingmachine,
A change in the tree is done by using different "moves", which all involve sampling values from some distribution. The list of current moves can be given by using the command `showmoves`, and a couple of graphical examples are given in [Appendix 3](https://github.com/NBISweden/MrBayes/blob/develop/doc/manual/src/Appendix_Fig3.pdf) in the manual.  Hence, any new branch length will be assigned a new numerical value based on the exact "move" involved.
/Johan

**Comment by computingmachine** [comment]
Hi Johan,
Thanks for the quick reply! Since I am a beginner to C and MrBayes. I also want to work with the source code. Could you please let me know which file contains the tree proposal process? like the process in Appendix A
Yuan

**Comment by nylander** [comment]
@computingmachine 
That would be `proposal.c`, to start with.
/Johan
