### ISSUE TITLE
Parsmodel not working

### ISSUE THREAD

**Issue by ronquist** [NBISweden/MrBayes#154]
### What is the current observed behaviour?

Stops after warning messages

### What is the expected/wanted behaviour?

Analysis should start

### How may we reproduce this bug?

To reproduce:

```
begin  mrbayes;
    exe primates.nex;
    lset parsmodel=yes;
    mcmc;
end;    
```

### What is the environment that you run MrBayes in?
  - Mac OS X
  - develop branch

```
Version:   3.2.7a
Features:  SSE AVX FMA Beagle readline
Host type: x86_64-apple-darwin18.7.0 (CPU: x86_64)
Compiler:  clang 11.0.0
```

**Comment by andkaha** [comment]
This has been corrected no the `develop` branch.
