### ISSUE TITLE
Cannot specify amino acid substitution rate less than 0.00

### ISSUE THREAD

**Issue by chainorato** [NBISweden/MrBayes#157]
Dear developers,

Since the amino-acid substitution model FLU (http://giphy.pasteur.fr/empirical-models-of-amino-acid-substitution/FLU.dat) is not included in MrBayes, I used a GTR model to assign the rate parameters of the FLU model instead. The problem occurs after I specified the model as follows;

`PRSET applyto=(16) aarevmatpr=fixed(0.138658764751059,0.0533665787145181,0.584852305649886,0.0264470951166826,0.353753981649393,1.4842345032161,1.13231312248046,0.214757862168721,0.149926734229061,0.0231169515264061,0.474333610192982,0.0587454231508643,0.0804909094320368,0.659311477863896,3.01134451903854,5.4182981753166,0.195966354027106,0.0182892882245349,3.53200526987468,0.161000889039552,0.00677184253227681,0.16720700818221,3.29271694159791,0.124897616909194,1.19062446519178,1.87956993845887,0.246117171830255,0.296045557460629,15.3000966197798,0.890162345593224,0.0160550314767596,0.154027179890711,0.950138410087378,0.183076905018197,1.36942940801512,0.0998554972524385,0.103964386383736,7.73739287051356,0.0000130249856764315,0.530642655337477,0.0616521921873234,0.322524647863997,1.38709603234116,0.21857197541607,0.000835873174542931,2.6468479652886,0.00525168778853117,0.000836445615590923,0.0364417719063219,3.88131053061457,2.14033231636063,0.000536284040016542,0.373101926513925,0.0102575172450253,0.014132062548787,0.145469388422239,5.37051127867923,1.93483278448943,0.887570549414031,0.0140859174993809,0.00573068208525287,0.290042980143818,0.0417629637305017,0.0000010600102849456,0.188539456415654,0.338372183381345,0.135481232622983,0.000014893873721753,0.525398542949365,0.297123975243582,0.00254733397966779,0.0000000000391106992668137,0.116941459124876,0.0218446166959521,0.00111215807314139,0.00561362724916376,0.00000383228119049152,0.111457310321926,0.10405366623526,0.000000000000159312060172652,0.336263344504404,0.011975265782196,0.0941066800969967,0.601692431136271,0.0549045639492389,1.19562912226203,0.108051341246072,5.33031341222104,0.0288399502994541,1.02036695531654,2.559587177122,0.190259181297527,0.0326806570137471,0.712769599068934,0.487822498528951,0.60234096342392,0.0440205200833047,0.0722059354079545,0.406697814049488,1.59309882471598,0.256491863423002,0.0142107118685268,0.016499535540562,3.88148880863814,0.313974351356074,0.00100350082518749,0.319558828428154,0.307140298031341,0.2801248951174,0.155245492137294,0.104092870343653,0.285047948309311,0.0587745274250666,0.0000162662283098296,0.00651622937676521,0.264148929349066,0.00150046692269255,0.00123664495412902,0.0386317614553493,1.58564657669139,0.0188080299490973,0.196486447133033,0.0748149970972622,0.337229618868315,0.243190142026506,0.321611693603646,0.347302791211758,0.00127350890508147,0.119028506158521,0.924466914225534,0.580704249811294,0.368713573381758,0.0223729191088972,6.44895444648517,0.0986313546653266,3.51207228207807,0.227707997165566,9.01795420287895,1.46335727834648,0.0805433268150369,0.290381075260226,2.90405228596936,0.0321321499585514,0.273934263183281,14.3940521944257,0.129223639195248,6.74693648486614,2.98680003596399,0.634308520867322,0.570766693213698,0.0449263566753846,0.431277662888057,0.340058468374384,0.890598579382591,1.33129161941264,0.319895904499071,0.195750631825315,0.283807671568883,1.52696419998775,0.0000497641445484395,0.0124162215506117,0.0731279296372675,0.279910508981581,0.0568693216513547,0.00702658828739369,2.03151132062208,0.0704600385245663,0.874272174533394,4.90484223478739,0.0071324304661639,0.996685669575839,0.000134906239484254,0.814753093809928,5.39392424532822,0.592587985458668,2.08738534433198,0.54225109402693,0.000431020702277328,0.000182294881489116,0.0589719751511691,2.2068599339404,0.0998357527014247,0.392552239890831,0.0882564232979724,0.207066205546908,0.124898020409882,0.654109108255219,0.42775543040588,0.256900461407996,0.167581646770807) statefreqpr=fixed(empirical);
`

>       Rate value cannot be less than 0.00
>       Error when setting parameter "Aarevmatpr" (2)
>       The error occurred when reading char. 718-738 on line 69
>          in the file 'bayes_PROTEIN.nex' 

Although it states the "Rate value cannot be less than 0.00", I looked through the file model.c and found the following line;

`MrBayesPrint ("%s   Rate value cannot be less than %1.2lf\n", spacer, `0.0001);`

I guessed that actually the problem might occur because some of my own specified rate value is less than 0.0001 (such as 0.000000000000159312060172652). Is there anyways I could proceed if I would like to keep this rate matrix for analysis with MrBayes? Thank you in advance.

**Comment by ronquist** [comment]
This is a correct observation; MrBayes does not allow rates that small. I changed this in the branch feature/issue-157. Now we use a macro, AA_RATE_MIN, and it is set to 1E-15. I will post a pull request for this code to be included in the develop branch and will close this issue now.

NB! To involve the fixed rate matrix, you need to also specify "prset aamodelpr=fixed(gtr)". Also note that values this small can be more conveniently specified in most cases using scientific format (1.6e-13 instead of 0.000000...16). You can mix fixed-point and scientific-format values; MrBayes will read them correctly in either case.

**Comment by chainorato** [comment]
Thank you very much for your help @ronquist  :)
