### ISSUE TITLE
Runs fail when covarion model is invoked with MrBayes 3.2.7a on CIPRES

### ISSUE THREAD

**Issue by willbour** [NBISweden/MrBayes#160]
All MrBayes analyses fail on CIPRES when covarion substitution model is invoked for nucleotide data (either on the GUI or in a Bayes block in the input file). Help anyone? Thanks

**Comment by nylander** [comment]
Note to self:

- Try covarion substitution model on nucleotide data using v3.2.7a on any other platform. Does it even work?

**Comment by willbour** [comment]
Hi Johan,
Can you advise me as to how I might be able to successfully invoke the covarion model in any version of MrBayes?
Thanks much,
Bill Bourland

**Comment by nylander** [comment]
Hi,
I can confirm that MrBayes crashes when using `lset covarion = yes;`. This is when compiling the current develop branch using default settings on GNU/Linux, gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04).

It seems to work, however, when the code is compiled **without** the BEAGLE library:
```
git clone https://github.com/NBISweden/MrBayes.git && cd MrBayes
./configure --without-beagle && make
src/mb -v
src/mb -i examples/primates.nex <<< "lset covarion=yes;showmodel;mcmc nruns=1 nchains=1 ngen=10000;sump;quit"
...
```

Whereas using BEAGLE didn't work on my machine:
```
make clean && ./configure --with-beagle=yes && make
src/mb -v
src/mb -i examples/primates.nex <<< "lset covarion=yes;showmodel;mcmc nruns=1 nchains=1 ngen=10000;sump;quit"
mb: /path/to/MrBayes/beagle/beagle-lib/libhmsbeagle/GPU/BeagleGPUImpl.hpp:864: int beagle::gpu::cuda::BeagleGPUImpl<Real>::setTipStates(int, const int*) [with Real = float]: Assertion `kLastCompactBufferIndex >= 0 && kLastCompactBufferIndex < kCompactBufferCount' failed.
Aborted (core dumped)
```

**Comment by andkaha** [comment]
It seems to be related to Cuda in Beagle somehow, as using a Beagle built without GPU support does not make the given command fail.

**Comment by willbour** [comment]
Hi Johan,
Thank you so much for this info. 
Since I’m a bit of a simpleton in these matters could you advise me how to proceed? I currently have MrBayes installed as 
Version:   3.2.7a
Features:  SSE AVX FMA MPI
Host type: x86_64-apple-darwin18.7.0 (CPU: x86_64)
Compiler:  clang 10.0.1

Do I need to uninstall this before installing the version with Cuda or Beagle?

Also, why do runs invoking covariant model fail on MrBayes Cipres portal even when Beagle is disabled?

Thanks,
Bill Bourland

**Comment by ronquist** [comment]
The immediate problem here is that the covarion model is not supported by the current beagle implementation in MrBayes. I have added a check now to switch over to the default likelihood calculator, so that even the beagle-enabled version will handle the covarion model correctly. This is in branch feature/issue-160, and I will post a pull request shortly to get this included in the develop branch. I am not sure what is going on in the MrBayes Cipres portal when Beagle is disabled; please post that as a separate issue with some means for us to replicate that behavior if it persists.
