### ISSUE TITLE
Individual trees from the posterior distribution of a FBD analysis have funny branch lengths

### ISSUE THREAD

**Issue by ivanlfm** [NBISweden/MrBayes#163]
I have just run a dated analysis in MrBayes using the fossilized birth-death model. I can summarize the consensus and it displays the correct ages using the sumt command. However, when I look at individual trees from the posterior distribution (from the .t files), the branch lengths look funny and have non-sense values (e.g. the fossils have ages outside the specified priors or the ages are between 0 and 1). Reading the trees from the .t file in other software (e.g. FigTree, or importing them into R using either ape's read.nexus or equivalent functions from treeio, phyloch and phylotate) also returns the incorrect branch lengths. Getting correct branch lengths for the individual trees would be important for me as I want to run analyses over the individual trees of the posterior distribution, not the consensus.

I suspect this is not a bug, but rather a feature of how MrBayes annotates the branch lengths in individual trees. Is there any way to recover the "correct" ages for these individual trees?

**Comment by nylander** [comment]
Dear @ivanlfm 

I'm not totally clear on how your branch lengths should look like when being "correct", so I'm not sure if this is a bug description or not. Taking a guess,  perhaps this has to do with the special tree format MrBayes uses for the output of the trees from a clock analysis? One example (just the first part of the tree description displayed):

```
tree gen.1000[&B Igrbranchlens{all}] = [&R] [&clockrate=1.864940614781551e-03] (1:1.410537487561901e-01[&B Igrbranchlens{all} 4.688356009259061e-02],((((50:7.963060926317082e ...
```

There is a `&clockrate=` annotation that applies to the whole tree, and you have to use that if you wish to transform the mb tree from having branch lengths as substitutions per site to time units. Personally I use a script ([Burntrees](https://github.com/nylander/Burntrees) , try the `--myr` argument) to do the transformation for me.

We are currently adding the option to have MrBayes write the trees in different output formats.

Cheers
Johan

**Comment by ivanlfm** [comment]
Dear Dr. Nylander
Many thanks for you detailed answer. I do not think it is a bug, the only issue is reading the special annotation into other software. The script you sent should solve my problem -- I will give it a try.
Thank you very much again.Best regards,Ivan
--
Dr. Ivan L. F. Magalhaes

Postdoctoral fellow — División AracnologíaMuseo Argentino de Ciencias Naturales "Bernardino Rivadavia" 
Av. Ángel Gallardo 470, C1405DJR, Buenos Aires, Argentina+54 11 4982-8370 ext. 169researchgate.net/profile/Ivan_Magalhaes
Twitter: @6eyes8legs 

    Em quarta-feira, 8 de abril de 2020 19:05:58 GMT-3, Johan Nylander <notifications@github.com> escreveu:  
 
 


Dear @ivanlfm

I'm not totally clear on how your branch lengths should look like when being "correct", so I'm not sure if this is a bug description or not. Taking a guess, perhaps this has to do with the special tree format MrBayes uses for the output of the trees from a clock analysis? One example (just the first part of the tree description displayed):
tree gen.1000[&B Igrbranchlens{all}] = [&R] [&clockrate=1.864940614781551e-03] (1:1.410537487561901e-01[&B Igrbranchlens{all} 4.688356009259061e-02],((((50:7.963060926317082e ...

There is a &clockrate= annotation that applies to the whole tree, and you have to use that if you wish to transform the mb tree from having branch lengths as substitutions per site to time units. Personally I use a script (Burntrees , try the --myr argument) to do the transformation for me.

We are currently adding the option to have MrBayes write the trees in different output formats.

Cheers
Johan

**Comment by ivanlfm** [comment]
Dear Dr. Nylander, 

Many thanks for the response. I do not think it is a bug, but rather a problem with other software being unable to read MrBayes' special annotation.

The Burntrees script worked perfectly fine and solved the problem entirely -- thank you so much for this!

Best,
Ivan

**Comment by nylander** [comment]
Closing
