### ISSUE TITLE
Could not find parameter "Statefreqmodel"

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#166]
User contributed bug report:

Hi,

I was happy to find the latest version of MrBayes with the non-stationary model. On my system (Ubuntu 18.04) it compiled well, both with beagle and openmpi unlike older versions which were a bit troublesome (mostly because of beagle). However, there was an error when I tried to use the non-stationary model as follows,
```
MrBayes > lset Statefreqmodel=Mixed

   Could not find parameter "Statefreqmodel"
```
I downloaded the source code from the **"feature/Seraina”** branch on github.

Could you please look into this. Thanks.

**Comment by ronquist** [comment]
The feature/Seraina branch is still not tested extensively, but the code now runs for simple examples. The keyword is now statefrmod but statefreqmodel is recognized as a synonym. I will close this issue now. I will test the code a little bit more, and also check potentially related issues before posting a pull request to include the code in the develop branch.
