### ISSUE TITLE
Is Mr Bayes 3.2.7a compatible with Catalina 10.15.4 (19E287)?

### ISSUE THREAD

**Issue by dtsingh** [NBISweden/MrBayes#169]
I used Mr Bayes several times on my iMac and on remote Linux server without any issues earlier.
After upgrading my iMac to the latest version of Catalina, I am not able to execute it even though I am able to successfully download the latest version of Mr Bayes using Homebrew. It's not able to parse the example files also. Gives some weird error message saying "the file...not found".
 Is the latest version of Mr Bayes compatible with latest version of Catalina?

**Comment by dtsingh** [comment]
This is the Error:
MrBayes > execute primates.nex

   Executing file "primates.nex"
   Could not open file "primates.nex"

   Returning execution to command line ...

   Error in command "Execute"

**Comment by andkaha** [comment]
The fact that you're able to start the program shows that it is compatible. Where is the file `primates.nex` in relation to your current directory when you run the `execute` command?

**Comment by dtsingh** [comment]
Oops!! Forgot to give the path...It works fine now..:)!! Thank you mate!!
