### ISSUE TITLE
Move test files

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/MrBayes#17]
We need to move test file and other documents inte GitHub.

Location of these now?

**Comment by ronquist** [comment]
They are in the test and documentation folders on SourceForge.

**Comment by ronquist** [comment]
We also should move the examples folder over as is. Previously, we kept one examples folder for releases, and one for testing purposes. It would make sense to keep that division. The same applies to documentation, where we can have one folder for technical documentation, latex source files etc, and one for release docs.

**Comment by kusalananda** [comment]
The release examples are already in place, see `examples/` in the top of the repository.  I will move the other things. I have also already put the release documents (formatted manuals) into `doc/`.

I propose that I create a top-level `test/` directory containing the test examples, and put document sources under `src/doc/`.

I haven't looked at the original test things, so I might change my mind...

**Comment by kusalananda** [comment]
I've added tests to `test/`, and document sources to `doc/src/`. I've also added a tutorial to `doc/tutorial`.  This is on the `feature/add_missing_bits_from_sf`.

I'm not sure where to add the extended examples.  Some of them overlap with what's already in `examples/`.  Do we want to keep them as two separate sets, or should the larger set replace the smaller set currently in `examples/`?

When doing `make dist` (to create a `tar` archive for a Unix release), it's fairly easy to pick the specific examples that should go into the archive file, so replacing the current examples with the larger set is not necessarily an issue.

However, the examples currently in `examples/` all have _different contents_ than the corresponding files in the larger example collection.

**Comment by ronquist** [comment]
Yes, the examples/ files have been edited to be more suitable for tutorials and beginners. I say we keep all the "raw" test example files in a separate folder, even if they are just versions of the tidy ones in examples/ (intended for releases). If you wish, we can wait with including them. Otherwise you can just put them in an extra folder like "test_data" or something like that for now, and then I can try to clean the folder up later.

**Comment by kusalananda** [comment]
I'll put them in `test/data/`. Then I'll merge the branch to `develop`.

**Comment by kusalananda** [comment]
Done.
