### ISSUE TITLE
Move bug tracking database over from SourceForge

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/MrBayes#18]
The bug tracking database on SourceForge needs to move to GitHub issues.

It is currently unknown to me how this may be done.

**Comment by ronquist** [comment]
I suggest we go through the existing open tickets (16 bugs and 2 feature requests). If we cannot close them soonish, we can add them manually to the github issues and close them on SourceForge with a redirection notice to the github issue. It does not seem important to me to move the bug tracking database over to github; it can remain on SourceForge.

**Comment by kusalananda** [comment]
New issues should be entered here though, not on SourceForge.

[Web-page](http://nbisweden.github.io/MrBayes/issues.html) needs updating.

**Comment by kusalananda** [comment]
Work has been done by @nylander .
