### ISSUE TITLE
Tutorial directory missing

### ISSUE THREAD

**Issue by ErikGobbo** [NBISweden/MrBayes#180]
There is no "Tutorial" directory in "doc"

### What is the current observed behaviour?
The configure and make files reference a "doc/Tutorial/Makefile.in" file which is missing, this produces an error during configuration and compiling

### How may we reproduce this bug?
Trying to clone the current repository, and install MrBayes as explained in README should reproduce the problem. The error is given while running "./configure", "make" and "make install"

### Would you be able to compile and run MrBayes to test fixes to this bug?
  - Yes, I know how to use `git` and how to compile MrBayes.

### What is the environment that you run MrBayes in?
  - Operating system (including variant and release): Debaian 10
  - Version of MrBayes: 3.2.6, I think
  - If possible, include the output of the `Version` command in MrBayes below: I installed it on another machine, I can't check it now

### Other information that may be of use to us in resolving this issue
A way around the problem is to use the -i flag of "make". This will ignore the error message and compile a functional version of MrBayes (although the "Tutorial" directory will still be missing)

**Comment by nylander** [comment]
Started addressing this in pull request #181

**Comment by andkaha** [comment]
The issue was an incomplete deletion of the tutorial subdirectory, along with some broken LaTeX markup in the manual. This has now been fixed. Thanks for the report!
