### ISSUE TITLE
'rl_attempted_completion_function’ undeclared  error  during compilation in centos 7.8.

### ISSUE THREAD

**Issue by rizwan3659** [NBISweden/MrBayes#182]
### What is the current observed behaviour?
'rl_attempted_completion_function’ undeclared  error  during compilation in centos 7.8. 

bayes.c: In function ‘main’:
bayes.c:190:5: error: ‘rl_attempted_completion_function’ undeclared (first use in this function)
     rl_attempted_completion_function = readline_completion;

### How may we reproduce this bug?

Steps to reproduce the bug:
  1. git cloned latest version of MrBayes of develop branch into the centos 7.8
  https://github.com/NBISweden/MrBayes.git
  2. configured it using ./configure.
  3. During compilation using make, Following error came
bayes.c: In function ‘main’:
bayes.c:190:5: error: ‘rl_attempted_completion_function’ undeclared (first use in this function)
     rl_attempted_completion_function = readline_completion;
  4.

### Would you be able to compile and run MrBayes to test fixes to this bug?
  - [ ] Yes, I know how to use `git` and how to compile MrBayes.
 

### What is the environment that you run MrBayes in?
  - Operating system (including variant and release): Centos 7.8
  - Version of MrBayes: 3.2.7a
  - If possible, include the output of the `Version` command in MrBayes below:

**Comment by rizwan3659** [comment]
1. Here is the solution (I have posted it so it can help someone else). This variable is defined in readline.h(GNU readline library).

 2. You can install readline library if not present in centos by following command
     yum install readline-devel

3.  last step is include readline.h in which above variable is defined by adding following line
#include <readline/readline.h> in bayes.c in src folder.

**Comment by rizwan3659** [comment]
https://github.com/NBISweden/MrBayes/pull/183
Here is the pull request.

**Comment by andkaha** [comment]
Are you running `configure` and `make` on two different machines? If the Readline library is not installed, Readline support should not be compiled into the project. It is the `configure` script that detects whether Readline is installed or not.  Likewise, if the Readline library is available, the correct headers will be found and included.

I'd be interested in seeing the full `config.log` and `src/config.h` after a failed run of `configure`+`make` on your CentOS system.

**Comment by rizwan3659** [comment]
Hi Sir, I am running configure and make on same system (centos 7.8). Readline library is not installed.
Here I am attaching config.log and zip file of config.h.  

[config.log](https://github.com/NBISweden/MrBayes/files/4707483/config.log)
[config.zip](https://github.com/NBISweden/MrBayes/files/4707496/config.zip)


.

**Comment by andkaha** [comment]
After installing `readline-devel` on your system, and re-running `configure`, does the un-modified MrBayes sources build properly?

**Comment by rizwan3659** [comment]
yes, after installing readline-devel. un-modified MrBayes sources build properly.
In config.h, even if I removed libreadline.so from /usr/lib64 and readline.h from /usr/include ,  then also
" HAVE_LIBREADLINE"  is set to 1 in config.h after configuring using ./configure . So it is going inside this code snippet in bayes.c and giving error  rl_attempted_completion_function undeclared.

#   ifdef HAVE_LIBREADLINE
    rl_attempted_completion_function = readline_completion;
    using_history();
#   endif

**Comment by andkaha** [comment]
Thanks! I can see the issue. When I'm back at work tomorrow, I'll commit a patch that disables Readline completely if the associated headers _or_ library can't be found by `configure`, which appears to be the cause of the issue that you're having according to the `config.log` that you provided.

**Comment by rizwan3659** [comment]
Okay sir :)

**Comment by andkaha** [comment]
A commit has been made to the `develop` branch that hopefully fixes this issue. Please reopen if it doesn't work for you.
