### ISSUE TITLE
Very long MCMC chains

### ISSUE THREAD

**Issue by andkaha** [NBISweden/MrBayes#186]
Received by private email:

>I am trying to run a stepping stone analysis of a difficult dataset,
resulting in long burninss and burnins within each step and, therefore,
requiring a very long MCMC chain to get a decent ESS of topology. However,
I can't seem to run a chain longer than 2E9 generations, with MrBayes just
reducing my ngen to this value, or lower before the run starts. Did I hit a
hard limit?

**Comment by andkaha** [comment]
This likely has something to do with the fact that `int` is being used for `Ngen` in the MCMC code.

**Comment by ronquist** [comment]
This is correct. The variable determining the number of ngenerations is an int in the MrBayes code. In typical compilers used today, this maps to a "long int", which has a maximum (signed) value just above 2E9. I have changed this now to a "long long int", with a guaranteed to hold numbers to at least 9E18. The total number of samples is still capped at 2E9; to run really long runs, make sure the sample frequency is such that the total number of samples remains below 2E9. There should be a warning issued if you break this limitation. The updated code is in the branch feature/issue-186, and will be merged into develop when @kusalananda has had a chance to look at it. I will close this issue now.

**Comment by zhangchicool** [comment]
This seems was not fixed correctly as two revert comments were merged into develop which revert the pervious changes
