### ISSUE TITLE
Dynamic scaling

### ISSUE THREAD

**Issue by ronquist** [NBISweden/MrBayes#19]
Scaling of likelihoods take a surprisingly large amount of time when using the standard 4by4 nucleotide models. Maxim added dynamic scaling code for the Beagle implementation but not for the native likelihoood calculators, which are faster. The dynamic scaling code adjusts the rescaling frequency so that you do not rescale likelihoods more often than needed to avoid numerical exceptions and achieve a reasonable level of precision. For typical-size trees and the 4by4 model, no rescaling is often needed. I added the infrastructure needed to support dynamic scaling for both Beagle and native calculators in December last year. In principle, it should be straightforward now to rewrite Maxim's dynamic scaling code (which is not so pretty C code) so that it works for both Beagle and native likelihood calculators.

**Comment by kusalananda** [comment]
Moved to `TODO` file.
