### ISSUE TITLE
Variable 'useBeagle' may be uninitialized when used

### ISSUE THREAD

**Issue by zhangchicool** [NBISweden/MrBayes#190]
In mcmc.c, line 5944, InitChainCondLikes (void)
        if (useBeagle == YES)
            indexStep = m->nCijkParts;
        else
            indexStep = 1;
There is a warning:  Variable 'useBeagle' may be uninitialized when used here. Please check.
Also check whether "useBeagle" or "m->useBeagle" should be used in various places.

**Comment by ronquist** [comment]
Thanks Chi! This is a bug that could potentially cause serious problems when computing likelihoods for advanced codon models (nCijkParts>1). Fixed now in branch feature/issue-190, and a pull request is pending. Will close this issue now.
