### ISSUE TITLE
Clarification of definition of average standard deviation of split frequencies

### ISSUE THREAD

**Issue by winni2k** [NBISweden/MrBayes#191]
I would like to know what the mathematical definition of the "Average Standard Deviation of Split Frequencies" (ASDSF) used in MrBayes 3.2 is. In my copy of the manual for MrBayes 3.2, section 5.3.7 cites

> Lakner, C., P. van der Mark, J. P. Huelsenbeck, B. Larget, and F. Ronquist. 2008. Efficiency of MCMC proposals in Bayesian phylogenetics. Systematic Biology. Pages 86–103.

for the definition of ASDSF. However, that paper does not appear to define ASDSF rigorously. All I can find in that paper is this:

> To diagnose convergence among tree samples, we used the average standard deviation of split frequencies (the estimated posterior probabilities of splits or taxon bipartitions).

Unfortunately, I do not understand what exactly this means. I have tried googling for the definition of ASDSF, but so far without success. Could I please get a definition here?

**Comment by ronquist** [comment]
There is a paragraph in the manual that describes the computation of the ASDSF:

> ASDSF is calculated by comparing split or clade frequencies across multiple independent MCMC runs
> that ideally should be started from different randomly chosen starting trees \citep{lakner08}.
> ASDSF should approach $0.0$ as runs converge to the same distribution. The frequencies of rare
> splits or clades are difficult to estimate accurately and these groupings are usually of marginal
> interest. Therefore, it may be advantageous to exclude them from the diagnostic. MrBayes allows the
> user to set a cutoff frequency (using the \ttt{minpartfreq} option for the \ttt{sumt} command); all
> splits or clades occurring minimally at that frequency (default value $0.10$), in at least one of
> the runs will be incorporated in the ASDSF.

I have now added an explicit definition of the ASDSF:

> ASDSF is calculated by comparing split or clade frequencies across multiple independent MCMC runs
> that ideally should be started from different randomly chosen starting trees \citep{lakner08}.
> Specifically, let $f_i^j$ be the fraction of the trees from run $i$ containing the split or clade (taxon
> bipartition) $j$. Then ASDSF is defined as
> \begin{equation*}
> \text{ASDSF} = \frac{1}{M} \sum_j \left( \sqrt{ \frac{1}{N-1} \sum_i (f_i^j - \bar{f}^j)^2} \, \right)
> \end{equation*}
> where $N$ is the number of runs, $M$ is the total number of splits or clades present in the tree
> samples being compared, and $\bar{f}^j$ is the mean fraction of trees across all runs containing
> split or clade $j$.

**Comment by ronquist** [comment]
I hope this is adequate and will close this issue now. The fix is in a separate issue branch but should be merged into develop shortly.

**Comment by winni2k** [comment]
That is perfect. Thank you so much!
