### ISSUE TITLE
Illegal instruction.....

### ISSUE THREAD

**Issue by ZhexueM** [NBISweden/MrBayes#194]
Hello together,
i had installed your program on our cluster with different functions: normal and MPI-enabled.

If one user want to work with your software, he takes the MPI-enabled Variation and get everytime the error-message: illegal instruction.

He want to run the software with this command:
srun mb <file>.nex > log.txt

So, can everybody help me here please?
Best regards from Berlin

Matthias

**Comment by andkaha** [comment]
Can you say something more about how you compiled the code? Can you reproduce the error yourself? Are the machine where the code was compiled and the machine where the code was run the same machine, or identical, or are the differences in libraries etc.?

Also, is `srun` the correct command to run MPI-enabled programs on your system? I'm more used to using `mpirun ... mb` (where `...` are various options).

**Comment by ZhexueM** [comment]
Hello,

well I compiled it on my MASTER – Server & saved it on CLUSTER – Volume.

All the Node, Server, etc. are on the same DEBIAN – Buster – Versions and the libraries are the same too.

 

So, what did you need more?

Best regard

 

 

Matthias

 

Von: Andreas Kusalananda Kähäri <notifications@github.com> 
Gesendet: Freitag, 3. Juli 2020 12:59
An: NBISweden/MrBayes <MrBayes@noreply.github.com>
Cc: ZhexueM <krawutschke@uni-potsdam.de>; Author <author@noreply.github.com>
Betreff: Re: [NBISweden/MrBayes] Illegal instruction..... (#194)

 

Can you say something more about how you compiled the code? Can you reproduce the error yourself? Are the machine where the code was compiled and the machine where the code was run the same machine, or identical, or are the differences in libraries etc.?

**Comment by zhangchicool** [comment]
Could you provide
1. computing environment, including the operating system and version 
2. details of the code compilation. including e.g. commands used to compile mrbayes
3. an example dataset and mrbayes commands that can be run to reproduce the error
