### ISSUE TITLE
The readline library does not play well with MPI

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/MrBayes#2]
Whenever MrBayes is compiled with an MPI C compiler (OpenMPI/MPICH), the readline library seems to stop working entirely (no command history within an interactive session, and no command tab-completion). I've seen other people have problem with this, so I don't think it's a bug in the actual MrBayes code. However, it's an issue, so I'll add it here.

**Comment by kusalananda** [comment]
Current `configure.ac` (on the `develop` branch) disables Readline support if an MPI C compiler is used. This doesn't close this issue.

**Comment by ronquist** [comment]
I looked into this a long time ago. Then there was no easy solution, because of conflicts between OpenMPI and readline. If the situation is still the same, I suggest we close this issue and disable readline in the MPI version.

**Comment by kusalananda** [comment]
Closing issue. Current behaviour is acceptable.
