### ISSUE TITLE
mpirun slowdown in virtualbox (not a bug)

### ISSUE THREAD

**Issue by roussine** [NBISweden/MrBayes#217]
Hello,
will be grateful if someone can comment.

After some exercises with an MPI compilation of mb, I find a surprising behaviour: up to a certain number of -np (CPU cores) it acquires a nice speed-up, however, after a certain threshold of processes, the performance becomes worse. It deteriorates further if any other (non-mpi) jobs are set running on the same machine. Total CPU load on host is also "unstable" in a sense that it "jumps" from ~20 to 50% every 5-7 sec, although it should consume ~80% considering the number of running virtual processes. The settings and virtualisations are all set up, resources allocated in excess, dependencies, make's, etc. seem to have come in place.

The schema I'm using is rather multifaceted and includes "variables" like openmpi, virtualbox, Win-7 host. 
However, decided to post here first, before turning to mpi-oriented forums, as someone must have had some experience with "virtual" mpi-mrbayes.

```
Host: Win 7 64x, Intel Xeon E5-2650 v2 (2 CPU = 32 virtual CPU total)
Guest OS: Ubuntu 14 (Biolinux 8)
VirtualBox: ver. 6x
MrBayes: 
   MrBayes 3.2.7a
   Features:  SSE AVX Beagle MPI
   Host type: x86_64-unknown-linux-gnu (CPU: x86_64)
   Compiler:  gnu 4.8.4
```

Will be happy to share any further info and accept any comment. Thanks in advance.
Leo

**Comment by andkaha** [comment]
Hi,

You don't say exactly what analysis you're running, how you run it, and on what data, and I don't know exactly how well virtual CPUs in VirtualBox scales depending on physical CPUs in the host.

In general, for problems that are not embarrassingly parallel (i.e. problems that require data to be  transferred between instances of the program during the course of computation), what you're seeing is normal and expected.

As you add more instances of MrBayes (past a certain point depending on both analysis set-up and hardware characteristics), the communication starts to take more time than what the actual useful computation takes, and efficiency decreases.

Regards,
Andreas

**Comment by roussine** [comment]
Hello Andreas - and thanks for the notice.

The analyses are rather conventional  design, a covarion modelling of  ~1.5k DNA for about 150+ taxa. Indeed, virtual CPUs downscale relative to physical ones, however usually by a factor of ~0.9-0.95 only.
Physical Win-7 host is dual 8-core CPU with HT (= 32 logical CPUs).

_Observed_: 
- if 4 runs (4 chains each) are launched in a single mpirun for cross-checking, it builds up to 800 h estimated time (and finally stucks, as it appears), while it is ~160 h on a physical multi-CPU linux machine on exactly the same number of CPUs.
- if 4 runs are launched as separate mpiruns successively (1 h lapse), the estimated time drops to ~200 h initially but would increase 2+ folds as more runs are added; the resources are being consumed accordingly (both virtual and physical) but mpi performance degrades quickly.
- if one more run is added to exceed 16 virtual CPUs, the second host multicore CPU becomes involved but overall performance drops even further, not exceeding 50% total host CPU load and behaving in "jumps" from ~20 to 50% every several sec.  

_Question_: why an mpi schema is associated with such a degradation, while CPU and RAM resources are in excess and remain not fully used by the virtual mpiruns? 
Shall it be attributed to a CPU architecture of the host or rather to virtualisation interface or other causes. And are there possible roundabouts.

Thank you indeed for advising.
Leo

**Comment by nylander** [comment]
Dear @roussine 
Thank you so much for your contribution. It is unclear to us if what you describe is specific to the code for MrBayes, or if it is more related to a general behavior of your combination of OS + Virtualization + MPI, etc. We expect the latter. If you suspect this is indeed an issue with the code, we are happy to re open this issue. Closing now.
/Jhan
