### ISSUE TITLE
Bug while executing my .nex file

### ISSUE THREAD

**Issue by Deisiany** [NBISweden/MrBayes#228]
### How may we reproduce this bug?

Steps to reproduce the bug:
  1. execute ex.nex file
  2.
  3.
  4.

### Would you be able to compile and run MrBayes to test fixes to this bug?
  - [ ] Yes, I know how to use `git` and how to compile MrBayes.
  - [ ] No, sorry.
- [ x
<img width="1440" alt="Screen Shot 2020-11-25 at 08 50 33" src="https://user-images.githubusercontent.com/70155730/100236157-4b4df000-2efb-11eb-8874-f5ebe2fa1ac8.png">
] Maybe, sorry I am new at these.

### What is the environment that you run MrBayes in?
  - Operating system (including variant and release):
  - Version of MrBayes:
  - If possible, include the output of the `Version` command in MrBayes below:

**Comment by nylander** [comment]
Dear @Deisiany

Thank you for your note. This doesn't strike me as a bug in the code of MrBayes. My suspicion is the format of the input file.

The software states: 
`The error occurred when reading char. 3-3 on line 1032 in the file 'ARF.ex.nex'`.
How does that character (on line 1032) look like?

Common mistakes while formatting Nexus files are incorrect number of characters specified for `nchar`, in combination with situations where not all sequences are or the correct length. In addition, special (control) characters are sometimes added to the text files, and/or line ending/file encoding (win versus unix,mac) may also contribute to these errors.

Closing this issue now. If you feel that this is indeed a bug in the code, feel free to reopen this issue.
