### ISSUE TITLE
Birth-Death model parameterization

### ISSUE THREAD

**Issue by ronquist** [NBISweden/MrBayes#23]
In previous versions of MrBayes we had the BD model parameterized so that you had a separate prior on tree age, and then given that prior a density on the tree given the BD parameters. Some years ago, it was changed to use Tanja's BD density that integrates out the age of the tree given a uniform prior from 0 to infinity. However, this is probably for many empirical problems a distribution that puts too much probability on really old trees. Also, it is inconsistent with the more recently added FBD model. So I think we should change the BD model implementation back so that it uses the conditional density, given the tree age, and then use a separate density on tree age, like we do for the FBD model. Would Chi be willing to look at this?

**Comment by zhangchicool** [comment]
It will wait a long time for me to do this, as i will be in new zealand and beijing during August. 
I may have time to look at this in September the earliest.

**Comment by zhangchicool** [comment]
I also updated the dating tutorial (in doc/tutorial/), to incorporate this change.

**Comment by kusalananda** [comment]
@zhangchicool, I moved the tutorial document sources into `doc/tutorial/src`, I hope you don't mind...

**Comment by zhangchicool** [comment]
Not at all. Thanks, @kusalananda

**Comment by kusalananda** [comment]
Fredrik is happy with this. Closing issue.
