### ISSUE TITLE
unlink kmixture rate models

### ISSUE THREAD

**Issue by onmikula** [NBISweden/MrBayes#234]
Hello,
how can I unlink the kmixture rate models of different partitions? In the current version of the manual (dated July 2020) I could not find any information about this.
Thank you in advance for any advice!
Ondrej Mikula

**Comment by nylander** [comment]
Dear @onmikula 
The rate variation within each partition will be modeled with a flat Dirichlet with fixed mean = 1. The rate variation among partitions would be taken care of when you use `prset ratepr = variable`. If you would have used e.g., `lset rates=gamma`, then the gamma-shape parameter can be free to vary, and may be "linked" or "unlinked" among partitions (i.e. "have different values"). For `lset rates=kmixture` the mean is always 1.0.
