### ISSUE TITLE
Use readline to allow command history

### ISSUE THREAD

**Issue by ftyers** [NBISweden/MrBayes#236]
This is a feature request / enhancement request. Please feel free to remove it if it is inappropriate. It would be great to use [GNU readline](http://web.mit.edu/gnu/doc/html/rlman_toc.html#SEC21) to be able to edit commands and have history.

**Comment by andkaha** [comment]
Hi,

The GNU Readline library will be used if it's available, unless MrBayes is compiled with MPI support (this is a known incompatibility).  MrBayes does not use the library's persistent history feature, but you ought to be able to recall commands from the current interactive session, as well as editing whatever you're typing using familiar editing keystrokes.

If you want persistent command history, I can recommend `rlwrap` (a Readline wrapper utility).  This should be available on most Unix systems.  See the `rlwrap` manual for how to tweak it.

See also the very end of the MrBayes' `INSTALL` document, where most of what I've already said is mentioned: https://github.com/NBISweden/MrBayes/blob/develop/INSTALL

Regards,
Andreas
