### ISSUE TITLE
URGENT: Need more info: Ancestral sequence reconstruction

### ISSUE THREAD

**Issue by LysSanzMoreta** [NBISweden/MrBayes#240]
Hi!

I am trying to reconstruct a sequence for every node in the tree. I have been following the manual the best I could and I only get 1 sequence as an output when parsing it out. I use this inside my nexus file: 

```
begin mrbayes;

    [This block defines several different character sets that could be used in partitioning these data
    and then defines and enforces a partition called favored.]

    set autoclose=yes nowarn=yes;
    lset nst=6 rates=invgamma ngammacat=4; [GTR+I+G model]
    prset ratepr=variable;
    taxset MyTaxset = A1 A2 A3 A4 A5 A6 A7 A8 A9 A10; **--> Does this mean that it will reconstruct the ancestor from all these nodes?**
    constraint MyConstraint = MyTaxset;
    prset topologypr = constraints(MyConstraint);
    report ancstates=yes;
    mcmc nruns=1 nchains=1 ngen=50000 checkpoint=no; 
    sump;
    quit;

end;
```
I am not sure about: 

a) Do I need to give a tree topology as well somehow? I have a predefined tree topology

b) How to use taxset, constraint and topology in the right manner to obtain all the ancestral nodes. 

c) Taxset says that it caanot be given more than 30 taxon names....what if I have 50 leaves and therefore 50 ancestral nodes?Am I constrained to small datasets?

Thank you very much in advance for your help!

**Comment by zhangchicool** [comment]
From "help report": 
   Ancstates -- If this option is set to 'yes', MrBayes will print the pro-      
                bability of the ancestral states at all constrained nodes. Typ-  
                ically, you are interested in the ancestral states of only a few 
                characters and only at one node in the tree. To perform such     
                an analysis, first define and enforce a topology constraint      
                using 'constraint' and 'prset topologypr = constraints (...)'.   
                Then put the character(s) of interest in a separate partition and
                set MrBayes to report the ancestral states for that partition.   
                For instance, if the characters of interest are in partition 2,  
                use 'report applyto=(2) ancstates=yes' to force MrBayes to print 
                the probability of the ancestral states of those characters at   
                the constrained node to the '.p' file.  
You may try following this procedure to see if it works.

**Comment by zhangchicool** [comment]
From "help report": 
   Ancstates -- If this option is set to 'yes', MrBayes will print the pro-      
                bability of the ancestral states at all constrained nodes. Typ-  
                ically, you are interested in the ancestral states of only a few 
                characters and only at one node in the tree. To perform such     
                an analysis, first define and enforce a topology constraint      
                using 'constraint' and 'prset topologypr = constraints (...)'.   
                Then put the character(s) of interest in a separate partition and
                set MrBayes to report the ancestral states for that partition.   
                For instance, if the characters of interest are in partition 2,  
                use 'report applyto=(2) ancstates=yes' to force MrBayes to print 
                the probability of the ancestral states of those characters at   
                the constrained node to the '.p' file.  
You may try following this procedure to see if it works.

**Comment by LysSanzMoreta** [comment]
Thanks, I can try to investigate the .p file in the output, because the rest seems the same as I did

**Comment by nylander** [comment]
No feedback since last message. Seems to be OK?
Closing issue. Feel free to reopen if needed.
