### ISSUE TITLE
Unable te install MrBayes on Apple M1 hardware (arm CPU issue?)

### ISSUE THREAD

**Issue by andkaha** [NBISweden/MrBayes#241]
I failed to install mrbayes on Mac OS big sur M1 chip. Could anyone help me please, to solve the problem. thank you.

==> Installing mrbayes from brewsci/bio
Error: beagle: no bottle available!
You can try to install from source with:
  brew install --build-from-source beagle
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

brew install --build-from-source beagle
==> Downloading https://github.com/beagle-dev/beagle-lib/archive/v3.1.2.tar.gz
Already downloaded: /Users/yudhiratnanugraheni/Library/Caches/Homebrew/downloads/15c4619d743d3ff1013dea23aafc2d821f0565217f17f5eddc12aac4dd438a74--beagle-lib-3.1.2.tar.gz
==> ./autogen.sh
==> ./configure --prefix=/opt/homebrew/Cellar/beagle/3.1.2_1 --without-cuda --di
==> make install
Last 15 lines from /Users/yudhiratnanugraheni/Library/Logs/Homebrew/beagle/03.make:
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/mmintrin.h:394:19: error: use of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/mmintrin.h:352:19: note: '__builtin_arm_addg' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/mmintrin.h:394:19: error: first argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^                    ~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [libhmsbeagle_cpu_sse_la-BeagleCPUSSEPlugin.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

_Originally posted by @yudhiratna in https://github.com/NBISweden/MrBayes/issues/147#issuecomment-806337562_

**Comment by andkaha** [comment]
The MrBayes code uses x86 intrinsics.  It is uncertain whether these would be usable on an ARM CPU (a quick Google search tells me "no"). 

I don't currently have access to an Apple macOS machine running on an ARM CPU, so I can't tell you exactly how to proceed to install MrBayes on your hardware.  I would probably try to compile it with the x86 intrinsics turned off, but I wouldn't be able to tell you exactly how to do that.  Part of me would expect the `configure` script to handle that automatically, but the log output that you have included shows that it's not.

If you're able to use the GitHub source distribution of MrBayes, and to compile it your self from there, I would suggest trying to run the `configure` script with `--disable-{sse,avx,fma}` to see if that helps.

**Comment by cathynewman** [comment]
Running the `configure` script with `--disable-{sse,avx,fma}` seems to have worked for me! I'm on Macbook Air M1 (2020), macOS 11.2

I haven't tried running a whole analysis yet, but the install completed without errors, and `mb` initiates MrBayes as expected.

**Comment by cathynewman** [comment]
Test analysis completed. Runs as expected.

Additional info: I initially tried to install from source following the instructions on the GitHub. `configure` seemed to work, but then the install failed on `make && sudo make install`. I trashed the whole directory, downloaded the source again, and this time ran `configure` with the flag and the make install worked.

Thank you!

**Comment by andkaha** [comment]
I'm happy that the issue seems to have been resolved.  The code will not be running as quickly as it would do with the x86 intrinsics enabled, but it would hopefully _run_.

I'm closing this issue for the moment. Feel free to re-open it if needs be.
