### ISSUE TITLE
Average standard deviation bellow 0.01 but many ESS values are below 200?

### ISSUE THREAD

**Issue by ypchan** [NBISweden/MrBayes#243]
Dear Sir,

I am using Mrbayes for phylogenetic analysis. I found that I got the average stand deviation below 0.01, but the many ESS values checked by Tracer, are below 200. How to interpret this?

Best regards,
Yanpeng Chen

**Comment by zhangchicool** [comment]
ASDSF are diagnostics for tree topologies while ESS are diagnostics for the (continuous) parameters. It is likely the parameters are not sampled sufficiently so longer runs are needed.
