### ISSUE TITLE
sumt command error 

### ISSUE THREAD

**Issue by prasupad** [NBISweden/MrBayes#244]
I am been running an analysis for 3 weeks and it also stopped in between I restarted the analysis using "append=yes" command. My parameters for the analysis where :
########################################################
execute filename.nexus
prset aamodel=mixed
mcmc  nchains=1  ngen=XXXXXXXXX   
########################################################
error:
########################################################
MrBayes > sumt

   Summarizing trees in files "g-ve.nexus.run1.t" and "g-ve.nexus.run2.t"
   Using relative burnin ('relburnin=yes'), discarding the first 25 % of sampled trees
   Writing statistics to files g-ve.nexus.<parts|tstat|vstat|trprobs|con>
   Examining first file ...
   Found one tree block in file "g-ve.nexus.run1.t" with 67201 trees in last block
   Expecting the same number of trees in the last tree block of all files

   Tree reading status:

   0      10      20      30      40      50      60      70      80      90     100
   v-------v-------v-------v-------v-------v-------v-------v-------v-------v-------v
   *********   Expecting ', or ) or ['
   Instead found 'tree' in command 'Tree' at position 4
   Error in command "Tree"
#############################################################
Please help me so i can complete my thesis in time, Thank you in advance

**Comment by nylander** [comment]
I suspect error in file content of input files. Possible caused while/when attempting to restart. It seems as if the parser is missing a `;` (since it is looking for a `)`.
However, we would need to see the input files to be able to confirm this.
Furthermore, thesis is most probably finished by now (due to finish in 2021?), so closing this issue. Feel free to reopen with example data.

**Comment by abhitims** [comment]
I am also facing a similar issue. Mr bayes closed unexpectedly and i have added "end;" to the two .t files however when I run sumt, I get  "Expecting the same number of trees in the last tree block of all files". However, when I check in notepad the number of trees are the same.. Any help will be much appreciated.
  
  Setting sumt contype to Allcompat
   Summarizing trees in files "C:\Users\HP\Desktop\temp\MB_May24.nex.run1.t" and "C:\Users\HP\Desktop\temp\MB_May24.nex.run2.t"
   Using relative burnin ('relburnin=yes'), discarding the first 25 % of sampled trees
   Writing statistics to files C:\Users\HP\Desktop\temp\MB_May24.nex.<parts|tstat|vstat|trprobs|con>
   Examining first file ...
   Found one tree block in file "C:\Users\HP\Desktop\temp\MB_May24.nex.run1.t" with 3860 trees in last block
   Expecting the same number of trees in the last tree block of all files
