### ISSUE TITLE
 The average standard deviation of split frequencies

### ISSUE THREAD

**Issue by jojobmz** [NBISweden/MrBayes#245]
Dear Professor,
I'm a graduate student. Recently I used Mrbayes. The  "the average standard deviation of split frequencies“ can be seen during the operation, but I have closed the program. I want to find a file that can see this number, but I don't know how to find it.

Thank you.

**Comment by zhangchicool** [comment]
The ASDSF values are in the .mcmc file

**Comment by jojobmz** [comment]
> The ASDSF values are in the .mcmc file
Thank you very much! You have solved my problem.
