### ISSUE TITLE
Molecular Clock Dating

### ISSUE THREAD

**Issue by francicco** [NBISweden/MrBayes#246]
Hi,

I'm not writing to report issues. This is a question-related post. I'm trying to time calibrate a phylogeny using MrBayes, it's the first time I'm doing it and I want to make sure I'm not doing any major mistake.

It is a fairly recent phylogenetic framework. the root should be around 90My, with the majority of nodes I'd like to infer the splitting events younger than 15my. To calibrate nodes I'm using data from [timetree](http://www.timetree.org/). And I'm using 44 nuclear loci for 48 species.

These are the setting I'm using at the moment:

```
onstraint Root 100 = 1-34 36-48;
constraint Node1 100 = 1-14 17-23 25-34 36-48;
constraint Node2 100 = 1 2 5-8 12-14 17 19-21 23 25-27 29 30 32 36-41 43-47;

set Usebeagle=Yes Beagleresource=28 Beagledevice=GPU;
set beagleprecision = single;
set beaglesse = yes;
set partition=byGene;
set autoclose=yes nowarn=yes;
startvals tau = mystarttree V = mystarttree;
lset applyto=(all) nst=6 rates=gamma;
unlink statefreq=(all) revmat=(all) shape=(all);
prset applyto=(all) ratepr=variable;

calibrate
                Root=unif(76,102)
                Node1=unif(45,65)
                Node2=unif(6.4,19.7)
;

prset nodeagepr = calibrated;
prset clockratepr = lognorm(-7,0.6);
prset brlenspr=clock:birthdeath;
[prset brlenspr=clock:uniform;]
prset samplestrat = diversity;
prset sampleprob = 0.0001;
prset speciationpr = exp(10);
prset extinctionpr = beta(1,1);
prset treeagepr = offsetexp(76,102);
prset topologypr=constraints(Root,Node1,Node2);
```

Is there anything I need to change or some mistake I'm doing?

Thanks a lot
Francesco

**Comment by zhangchicool** [comment]
We can only deal with bug reports.
