### ISSUE TITLE
Error in execution 

### ISSUE THREAD

**Issue by siddharthk02** [NBISweden/MrBayes#249]
Exe Hymenoptera_DATE.nex;

   Executing file "Hymenoptera_DATE.nex"
   UNIX line termination
   Longest line length = 1078
   Parsing file
   Expecting NEXUS formatted file
   Reading data block
      Allocated taxon set
      Allocated matrix
      Defining new matrix with 114 taxa and 3268 characters
      Data is Mixed
         Data for partition 1 is Standard
         Data for partition 2 is DNA
      There are a total of 2 default data divisions
      Data matrix is interleaved
      Gaps coded as -
      Missing data coded as ?
      Taxon   1 -> Orthoptera
      Taxon   2 -> Paraneoptera
      Taxon   3 -> Chrysopidae
      Taxon   4 -> Raphidioptera
      Taxon   5 -> Coleo_Polyphaga
      Taxon   6 -> Coleo_Adephaga
      Taxon   7 -> Lepid_Micropterigidae
      Taxon   8 -> Lepid_Papilionidae
      Taxon   9 -> Mecoptera
      Taxon  10 -> Xyela
      Taxon  11 -> Macroxyela
      Taxon  12 -> Runaria
      Taxon  13 -> Paremphytus
      Taxon  14 -> Blasticotoma
      Taxon  15 -> Tenthredo
      Taxon  16 -> Aglaostigma
      Taxon  17 -> Dolerus
      Taxon  18 -> Selandria
      Taxon  19 -> Strongylogaster
      Taxon  20 -> Monophadnoides
      Taxon  21 -> Metallus
      Taxon  22 -> Athalia
      Taxon  23 -> Taxonus
      Taxon  24 -> Hoplocampa
      Taxon  25 -> Nematinus
      Taxon  26 -> Nematus
      Taxon  27 -> Cladius
      Taxon  28 -> Monoctenus
      Taxon  29 -> Gilpinia
      Taxon  30 -> Diprion
      Taxon  31 -> Cimbicinae
      Taxon  32 -> Abia
      Taxon  33 -> Corynis
      Taxon  34 -> Arge
      Taxon  35 -> Sterictiphora
      Taxon  36 -> Perga
      Taxon  37 -> Phylacteophaga
      Taxon  38 -> Lophyrotoma
      Taxon  39 -> Acordulecera
      Taxon  40 -> Decameria
      Taxon  41 -> Neurotoma
      Taxon  42 -> Onycholyda
      Taxon  43 -> Pamphilius
      Taxon  44 -> Cephalcia
      Taxon  45 -> Acantholyda
      Taxon  46 -> Megalodontesc
      Taxon  47 -> Megalodontessk
      Taxon  48 -> Cephus
      Taxon  49 -> Calameuta
      Taxon  50 -> Hartigia
      Taxon  51 -> Syntexis
      Taxon  52 -> Sirex
      Taxon  53 -> Xeris
      Taxon  54 -> Urocerus
      Taxon  55 -> Tremex
      Taxon  56 -> Xiphydria
      Taxon  57 -> Orussus
      Taxon  58 -> StephanidaeA
      Taxon  59 -> StephanidaeB
      Taxon  60 -> Megalyra
      Taxon  61 -> Trigonalidae
      Taxon  62 -> Chalcidoidea
      Taxon  63 -> Evanioidea
      Taxon  64 -> Ichneumonidae
      Taxon  65 -> Cynipoidea
      Taxon  66 -> ApoideaA
      Taxon  67 -> ApoideaB
      Taxon  68 -> ApoideaC
      Taxon  69 -> Vespidae
      Taxon  70 -> Triassoxyela
      Taxon  71 -> Asioxyela
      Taxon  72 -> Nigrimonticola
      Taxon  73 -> Gigantoxyelinae
      Taxon  74 -> Spathoxyela
      Taxon  75 -> Xyela_mesozoica
      Taxon  76 -> Angaridyela
      Taxon  77 -> Xyelotoma
      Taxon  78 -> Undatoma
      Taxon  79 -> Dahuratoma
      Taxon  80 -> Orthoptera
      Taxon  81 -> Paraneoptera
      Taxon  82 -> Chrysopidae
      Taxon  83 -> Raphidioptera
      Taxon  84 -> Coleo_Polyphaga
      Taxon  85 -> Coleo_Adephaga
      Taxon  86 -> Lepid_Micropterigidae
      Taxon  87 -> Lepid_Papilionidae
      Taxon  88 -> Mecoptera
      Taxon  89 -> Xyela
      Taxon  90 -> Macroxyela
      Taxon  91 -> Runaria
      Taxon  92 -> Paremphytus
      Taxon  93 -> Blasticotoma
      Taxon  94 -> Tenthredo
      Taxon  95 -> Aglaostigma
      Taxon  96 -> Dolerus
      Taxon  97 -> Selandria
      Taxon  98 -> Strongylogaster
      Taxon  99 -> Monophadnoides
      Taxon 100 -> Metallus
      Taxon 101 -> Athalia
      Taxon 102 -> Taxonus
      Taxon 103 -> Hoplocampa
      Taxon 104 -> Nematinus
      Taxon 105 -> Nematus
      Taxon 106 -> Cladius
      Taxon 107 -> Monoctenus
      Taxon 108 -> Gilpinia
      Taxon 109 -> Diprion
      Taxon 110 -> Cimbicinae
      Taxon 111 -> Abia
      Taxon 112 -> Corynis
      Taxon 113 -> Arge
      Taxon 114 -> Sterictiphora
      Could not find taxon Perga in the correct position in the list of taxa
      WARNING: Reallocation of zero size attempted. This is probably a bug. Problems may follow.
      WARNING: Reallocation of zero size attempted. This is probably a bug. Problems may follow.
      Deleting previously defined characters
      Deleting previously defined taxa
      Error when setting parameter "MatrixInfo" (2)
      The error occurred when reading char. 1-5 on line 127
         in the file 'Hymenoptera_DATE.nex'

**Comment by siddharthk02** [comment]
What should be done??

**Comment by andkaha** [comment]
Hi,

Since we can't see the actual data file that you are using, I can only suggest that you look at the "Perga" taxon (and the previous and next around that taxon, "Sterictiphora" and "Phylacteophaga") to see if there is some obvious error in the data that could be manually fixed. The error message indicates that there is something wrong with the "Perga" taxon.

**Comment by siddharthk02** [comment]
Ok
