### ISSUE TITLE
"Building the Beagle library for MrBayes" section in MrBayes' Linux installation instructions is outdated

### ISSUE THREAD

**Issue by caaguado** [NBISweden/MrBayes#254]
Hi there,

First of all, thanks A LOT for the incredible work done on MrBayes :-)

The "Building the Beagle library for MrBayes" section is MrBayes installation instructions for Linux
at: https://github.com/NBISweden/MrBayes/blob/develop/INSTALL:238

are, I'm afraid, outdated and not in sync with the latest beagle-lib Linux installation instructions at:
https://github.com/beagle-dev/beagle-lib/wiki/LinuxInstallInstructions

For example, the ./autogen.sh script doesn't seem to exist any longer on beagle-lib's GitHub repo:

Could you please kindly update and synchronize MrBayes instructions with the official ones from
the beagle-lib project?

Thanks a lot!

**Comment by andkaha** [comment]
Hi, and thanks for the report!
We will double-check the instructions, make sure they are up to date, and adjust them if needed.
We'll probably do this during the next couple of days.
