### ISSUE TITLE
Error in function: ConfirmAbortRun at line: 15511 in file: mcmc.c   Mcmc run continued ...

### ISSUE THREAD

**Issue by zzzygolden** [NBISweden/MrBayes#260]
I use morphology and DNA combined data as an input, set `mcmcp ngen=10000000` and submit my task in Linux. When MrBayes ran in insufficient generations it stopped. And its log output is:
   
```
        Average standard deviation of split frequencies: 0.005470
        623000 -- (-164520.244) (-164508.877) [-164114.194] (-164149.176) * [-164125.771] (-164508.524) (-164124.362) (-164140.780) -- 81:38:43
        624000 -- (-164529.369) (-164508.715) [-164106.839] (-164135.822) * (-164122.630) (-164512.593) [-164122.009] (-164150.927) -- 81:30:35
        634000 -- (-164526.318) (-164518.163) (-164127.091) [-164138.676] * (-164148.822) (-164535.934) (-164145.491) [-164115.804] -- 80:09:48
        636000 -- (-164517.073) (-164523.789) (-164122.106) [-164113.277] * [-164140.386] (-164536.369) (-164150.913) (-164112.990) -- 79:55:07
   Ctrl-C detected
   Do you really want to stop the run (y/n)?Error in function: ConfirmAbortRun at line: 15511 in file: mcmc.c   Mcmc run continued ...
   Ctrl-C detected
   Do you really want to stop the run (y/n)?Error in function: ConfirmAbortRun at line: 15511 in file: mcmc.c   Mcmc run continued ...
   Ctrl-C detected
   Do you really want to stop the run (y/n)?Error in function: ConfirmAbortRun at line: 15511 in file: mcmc.c   Mcmc run continued ...
   Ctrl-C detected
   Do you really want to stop the run (y/n)?Error in function: ConfirmAbortRun at line: 15511 in file: mcmc.c   Mcmc run continued ...
```
   
I cannot find the file `mcmc.c` and resubmit my task with code `mpirun -np 8 mb combined-mydata.nex -mcmcdiagn no -mcmcappend yes`, it stopped with different and insufficient generations everytime.

I use MrBayes 3.2.7 x86_64.

Maybe someone knows how to solve this problem and thank you very much!

**Comment by andkaha** [comment]
Hi @zzzygolden 

It looks as if you are running `mb` with MPI, and it seems like the `mb` that you are trying to run with MPI was not compiled to be run with MPI.

What does the interactive `Version` command output if you give it in `mb`?

The reason that I think you are trying to run an `mb` without MPI support is that the error message that is displayed can only be displayed when a non-MPI variant of the software receives a <kbd>Ctrl+C</kbd> key-press (or an interrupt signal).  That piece of code is _disabled_ in the `mb` with MPI support.

**Comment by zzzygolden** [comment]
Hi @kusalananda 

Thanks for your reply. 

I used `conda install MyBayes` to download and install MrBayes and also saw the `mb-mpi` file in my mrbayes directory. So I thinked MPI was useful. I tried MPI previously and it succeeded in running the whole generations. But the result is not converged and I reset parameters but it never ran sufficient generations again.

I'll try `mb` and my data is a little bit big so it may spend some time. I'll reply you in time when I get my output.

**Comment by andkaha** [comment]
@zzzygolden 

If you have an `mb-mpi` executable, then this is probably what you want to use with MPI (maybe something like `mpirun -np 8 mb-mpi combined-mydata.nex -mcmcdiagn no -mcmcappend yes`, looking at your initial message here).  I know about the existence of Conda, but I never use it myself, so I can't say much about that.

**Comment by zzzygolden** [comment]
Hi @kusalananda 

`mpirun -np 8 mb-mpi combined-mydata.nex -mcmcdiagn no -mcmcappend yes` runs well now. I think this is the problem!

Sorry to have taken up your time. Thank you very much!!!

**Comment by andkaha** [comment]
@zzzygolden 

I'm just happy we resolved fairly easily.

Take care!
