### ISSUE TITLE
Issue with MSC,  'prset popsizepr'

### ISSUE THREAD

**Issue by johnpatramanis** [NBISweden/MrBayes#275]
Steps to reproduce the bug:
  1. Run Commands in MSC_MrBayes.txt file, with CONCATINATED_o.nex in the same folder 
  2. Nexus files is attached (changed name to upload here, contains protein data for hominids + ancient protein data from recent publications)

### Would you be able to compile and run MrBayes to test fixes to this bug?
  - [x] No, sorry.

### What is the environment that you run MrBayes in?

- OS
  
Operating System: Red Hat Enterprise Linux 8.5 (Ootpa)
CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
Kernel: Linux 4.18.0-348.20.1.el8_5.x86_64

  - Version of MrBayes: 

   ---------------------------------------------------------------------------
  
 Version

MrBayes 3.2.7

Features:  SSE AVX FMA Beagle readline
Host type: x86_64-conda-linux-gnu (CPU: x86_64)
Compiler:  gnu 9.3.0

   ---------------------------------------------------------------------------

### Other information that may be of use to us in resolving this issue

Files to reproduce:
Commands:
[MSC_MrBayes.txt](https://github.com/NBISweden/MrBayes/files/9508271/MSC_MrBayes.txt)
Data:
[CONCATINATED_o_nex.txt](https://github.com/NBISweden/MrBayes/files/9508280/CONCATINATED_o_nex.txt)

**Comment by zhangchicool** [comment]
Should be fixed in commit 6ca48fed8004580c519856842d402501ad736dcf. This was because the command did not deal with protein data.
