### ISSUE TITLE
error while running mcmc using mpi version on ubuntu 22.04

### ISSUE THREAD

**Issue by jhcuarta** [NBISweden/MrBayes#276]
Hi 
While running the command line "mpirun -np 4 mb -i core_gene_alignment_ATCC.nex" and setting parameters, I'm not able to start analysis, I get the following error after mcmc command

Running benchmarks to automatically select fastest BEAGLE resource... --------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 2 with PID 0 on node jason exited on signal 9 (Killed).

Here is the output for version

MrBayes, Bayesian Analysis of Phylogeny
Version:   3.2.7a
Features:  SSE AVX FMA Beagle MPI
Host type: x86_64-unknown-linux-gnu (CPU: x86_64)
Compiler:  gnu 11.2.0

I was wondering if it might be related to BEAGLE library

**Comment by jowodo** [comment]
Hi, 

I've got a very similar error when running `mpirun -np 4 mb -i file.nex` in a slurm job. When I run the same command on the login node (where mb has been installed) it works correctly. 
The problem for was that the compute node CPU does not support AVX (see #280).
