### ISSUE TITLE
Error on MrBayes 3.2.7a x86_64

### ISSUE THREAD

**Issue by YordyC** [NBISweden/MrBayes#284]
Hi, I'm trying to run my data but MrBayes report to me a error. I have 17 sequences with a length >2000000. I've already try wit "interleave", but still reporting the same bug.

MrBayes > exe SCOutBayes.nex

   Executing file "SCOutBayes.nex"
   UNIX line termination
   Longest line length = 3006812
   Parsing file
   Expecting NEXUS formatted file
   Reading taxa block
      Allocated taxon set
      Defining new set of 17 taxa
   Exiting taxa block
   Reading characters block
      Allocated matrix
      Defining new character matrix with 3006800 characters
      Data is Dna
      Gaps coded as -
      Data matrix is interleaved
      Taxon  1 -> CJ
      Error while parsing a string. Token "GGCGCGGGGGCGGGGAGGCC...[followed by at least 99970  more charectors]" is too long.
      Maximum allowed length of a token is 99990
      The error occurred when reading char. 100067-100086 on line 10
         in the file 'SCOutBayes.nex'
         
         
    I appreciate your help.

**Comment by zhangchicool** [comment]
The longest line supported is 99990, as reported by the error message. You can shorten the number of charactors in each line if you use interleaved format. Refer to issue #113.
