### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [NBISweden/MrBayes#289]
:eyes: I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

:thought_balloon: Would you like to add more error handling for return values from functions like the following?
- [fflush](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fflush.html "Flush a stream.") ⇒ [DoSumt](https://github.com/NBISweden/MrBayes/blob/c5c730c1f030e0cae377f0edd56c85d00c005db2/src/sumpt.c#L5428)
- [puts](http://pubs.opengroup.org/onlinepubs/9699919799/functions/puts.html "Put a string on standard output.") ⇒ [main](https://github.com/NBISweden/MrBayes/blob/c5c730c1f030e0cae377f0edd56c85d00c005db2/src/bayes.c#L277)

**Comment by andkaha** [comment]
> 👀 I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.
> 
> 💭 Would you like to add more error handling for return values from functions like the following?
> 
> * [fflush](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fflush.html) ⇒ [DoSumt](https://github.com/NBISweden/MrBayes/blob/c5c730c1f030e0cae377f0edd56c85d00c005db2/src/sumpt.c#L5428)
> * [puts](http://pubs.opengroup.org/onlinepubs/9699919799/functions/puts.html) ⇒ [main](https://github.com/NBISweden/MrBayes/blob/c5c730c1f030e0cae377f0edd56c85d00c005db2/src/bayes.c#L277)

I fully agree that not checking the returned values from calls to library functions is potentially problematic and that it theoretically means that certain error conditions go unchecked, but this will not be fixed unless you can show that the program, when used in a typical environment, misbehaves as a consequence of not checking the return value of these calls. 

As mentioned in other responses to your issues, this project is in maintenance mode, and our current efforts concern dealing with bugs that are demonstratively causing issues for users.

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

:crystal_ball: Under which circumstances will you care more also for data output failures?

**Comment by andkaha** [comment]
> 💭 I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more. Would you like to detect every error situation as early as possible?

Yes, please, that would be nice.

> 
> 🔮 Under which circumstances will you care more also for data output failures?

When we have a user that describes the reproducible circumstances of their failed usage of the software.

**Comment by elfring** [comment]
>When we have a user that describes the reproducible circumstances of their failed usage of the software.

:thought_balloon: Would you like to test the discussed software components also with a device like “[/dev/full](https://en.wikipedia.org/wiki//dev/full "Documentation")”?

-----

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C,_C++) also for your software? :thinking:

**Comment by andkaha** [comment]
> > When we have a user that describes the reproducible circumstances of their failed usage of the software.
> 
> 💭 Would you like to test the discussed software components also with a device like “[/dev/full](https://en.wikipedia.org/wiki//dev/full)”?

A full disk is an external failure condition that the software does not have to recover gracefully from, or even detect specifically. Yes, it would be nice to have it do that, but, and this may come as a surprise to you, we don't have the resources to audit the code for these conditions.

> 
> How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C,_C++) also for your software? 🤔

Will my answer to this question resolve this issue?

**Comment by elfring** [comment]
>…, we don't have the resources to audit the code for these conditions.

:crystal_ball: I hope that corresponding development interests can eventually grow.
