### ISSUE TITLE
SSE code (possibly) generates element in wrong order

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/MrBayes#3]
From renqiang[at]nbjl.nankai.edu.cn:
[...] in the functions `CondLikeDown_Bin()` and `CondLikeDown_Bin_SSE()`, both are in the
file `likelihood.c`, while calculating `clP`, the sequence of accessing to elements in tiProbs (`tiPL[]` and `tiPR[]`) and conLikes (`clL[]` and `clR[]`) is different. I think this will result in a different `clP` between SSE algorithm and normal algorithm.

**Comment by kusalananda** [comment]
Looking at this, it seems as if renqiang is correct, and the following may be a fix (waiting for verification):

```
diff --git a/src/likelihood.c b/src/likelihood.c
index 9048683..1756d2b 100644
--- a/src/likelihood.c
+++ b/src/likelihood.c
@@ -155,12 +155,20 @@ int CondLikeDown_Bin_SSE (TreeNode *p, int division, int chain)
         for (c=0; c<m->numVecChars; c++)
             {
             m1 = _mm_load1_ps (&tiPL[0]);
+            m1 = _mm_loadh_pi(m1, &tiPL[2]);
+
             m2 = _mm_load1_ps (&tiPR[0]);
+            m2 = _mm_loadh_pi(m2, &tiPR[2]);
+
             m5 = _mm_mul_ps (m1, clL[0]);
             m6 = _mm_mul_ps (m2, clR[0]);

             m1 = _mm_load1_ps (&tiPL[1]);
+            m1 = _mm_loadh_pi(m1, &tipL[3]);
+
             m2 = _mm_load1_ps (&tiPR[1]);
+            m2 = _mm_loadh_pi(m2, &tiPR[3]);
+
             m3 = _mm_mul_ps (m1, clL[1]);
             m4 = _mm_mul_ps (m2, clR[1]);

@@ -169,20 +177,6 @@ int CondLikeDown_Bin_SSE (TreeNode *p, int division, int chain)

             *clP++ = _mm_mul_ps (m5, m6);

-            m1 = _mm_load1_ps (&tiPL[2]);
-            m2 = _mm_load1_ps (&tiPR[2]);
-            m5 = _mm_mul_ps (m1, clL[0]);
-            m6 = _mm_mul_ps (m2, clR[0]);
-
-            m1 = _mm_load1_ps (&tiPL[3]);
-            m2 = _mm_load1_ps (&tiPR[3]);
-            m3 = _mm_mul_ps (m1, clL[1]);
-            m4 = _mm_mul_ps (m2, clR[1]);
-
-            m5 = _mm_add_ps (m3, m5);
-            m6 = _mm_add_ps (m4, m6);
-
-            *clP++ = _mm_mul_ps (m5, m6);
             clL += 2;
             clR += 2;
             }
```

**Comment by kusalananda** [comment]
Looking at this, it seems as if renqiang is correct, and pull request #4  may be a fix (waiting for verification).

**Comment by ChanneRen** [comment]
Thanks for your attention and hard work. But I think this possible fix is also inconsistent with the non-SSE version. I try to implement a possible fix as following, just from my own view and I do not know if it is right. (Please pay attention to new definition of clL, pL and other variables.)
`
        /* find conditional likelihood pointers */
	clL =  m->condLikes[m->condLikeIndex[chain][p->left->index ]];
	clR =  m->condLikes[m->condLikeIndex[chain][p->right->index]];
	clP = (__m256 *) m->condLikes[m->condLikeIndex[chain][p->index]];
	
	/* find transition probabilities */
	pL = (__m256 *) m->tiProbs[m->tiProbsIndex[chain][p->left->index ]];
	pR = (__m256 *) m->tiProbs[m->tiProbsIndex[chain][p->right->index]];
	
	tclL = clL;
	tclR = clR;
	for(k=0; k<m->numGammaCats; k++)
	{
		for(c=0; c<m->numSSEChars; c++)
		{
			m1 = _mm_set_ps(tclL[1], tclL[0], tclL[1], tclL[0]);
			m2 = _mm_set_ps(tclR[1], tclR[0], tclR[1], tclR[0]);
			m3 = _mm_mul_ps(m1, pL[0]);
			m4 = _mm_mul_ps(m2, pR[0]);
			
			m1 = _mm_set_ps(tclL[3], tclL[2], tclL[3], tclL[2]);
			m2 = _mm_set_ps(tclR[3], tclR[2], tclR[3], tclR[2]);
			m5 = _mm_mul_ps(m1, pL[0]);
			m6 = _mm_mul_ps(m2, pR[0]);
			
			m1 = _mm_hadd_ps(m3, m5);
			m2 = _mm_hadd_ps(m4, m6);
			
			*clp++ = _mm_mul_ps(m1, m2);
			
			m1 = _mm_set_ps(tclL[5], tclL[4], tclL[5], tclL[4]);
			m2 = _mm_set_ps(tclR[5], tclR[4], tclR[5], tclR[4]);
			m3 = _mm_mul_ps(m1, pL[0]);
			m4 = _mm_mul_ps(m2, pR[0]);
			
			m1 = _mm_set_ps(tclL[7], tclL[6], tclL[7], tclL[6]);
			m2 = _mm_set_ps(tclR[7], tclR[6], tclR[7], tclR[6]);
			m5 = _mm_mul_ps(m1, pL[0]);
			m6 = _mm_mul_ps(m2, pR[0]);
			
			m1 = _mm_hadd_ps(m3, m5);
			m2 = _mm_hadd_ps(m4, m6);
			
			*clp++ = _mm_mul_ps(m1, m2);
			
			tclL += 8;
			tclR += 8;
		}
		pL++;
		pR++;
	}`

**Comment by kusalananda** [comment]
Thanks!  I need to look at this and talk to the original authors.

**Comment by ronquist** [comment]
The original code is actually correct. To make sure, I compiled MrBayes with and without SSE code enabled, then I ran an analysis with 10,000 generations with default settings for the taylor.nex dataset (restriction site data) in batch mode. Then I ran a diff on the result files from the two runs, and it looks like follows (complete diff):

<                             MrBayes v3.2.7-dev x86_64
---
>                         MrBayes v3.2.7-svn(r1079) x64
139c139
<       MCMC stamp = 2152339047
---
>       MCMC stamp = 2055055503
194c194
<       Using standard SSE likelihood calculator for division 1 (single-precision)
---
>       Using standard non-SSE likelihood calculator for division 1 (single-precision)
199,200c199,200
<          Chain 3 -- -1212.666891 -- 136.292669
<          Chain 4 -- -1219.254792 -- 136.292669
---
>          Chain 3 -- -1212.666893 -- 136.292669
>          Chain 4 -- -1219.254795 -- 136.292669
205,206c205,206
<          Chain 3 -- -1193.188909 -- 136.292669
<          Chain 4 -- -1208.264812 -- 136.292669
---
>          Chain 3 -- -1193.188911 -- 136.292669
>          Chain 4 -- -1208.264814 -- 136.292669
220c220
<        2000 -- (-889.514) [-879.146] (-930.216) (-894.684) * (-892.984) (-939.141) (-857.936) [-835.977] -- 0:00:00
---
>        2000 -- (-889.514) [-879.146] (-930.216) (-894.684) * (-892.984) (-939.141) (-857.936) [-835.977] -- 0:00:04
227c227
<        6000 -- [-759.697] (-764.561) (-754.904) (-805.713) * (-767.294) (-796.846) [-740.188] (-738.629) -- 0:00:00
---
>        6000 -- [-759.697] (-764.561) (-754.904) (-805.713) * (-767.294) (-796.846) [-740.188] (-738.629) -- 0:00:01
235,236c235,236
<       Analysis completed in 3 seconds
<       Analysis used 3.03 seconds of CPU time
---
>       Analysis completed in 1 second
>       Analysis used 2.35 seconds of CPU time

As you can see, the two functions CondLikeDown_Bin and CondLikeDown_Bin_SSE produce nearly identical results, only differing in the sixth decimal for two of eight chains, being completely identical for the other six chains. The first 10,000 generations of the chain also appear to behave identically.

Interestingly, it appear that the non-SSE code is faster. In previous versions of MrBayes, we did not actually use the SSE code for binary characters, and it is doubtful whether it makes any sense. Regardless, now it is used and the computations should be correct.

Neither of the two suggested fixes make much sense to me but I assume they are based on an incorrect understanding of the way the MrBayes SSE code stores conditional likelihoods, which is understandable given that it is not well documented in the code. The clL, clR and clP arrays store the conditional likelihoods for the first state for four different characters (as much as will fit into a 128-bit unit), the next 128-bit unit stores the cond likes for the second state for the same characters. The next 128-bit unit stores the cond likes for the first state of the next character etc. If you label the cond likes c_ij, where i is the character number and j the state, then the vectors store the likelihoods in the sequence (using 0-offset indices): c_00, c_10, c_20, c_30, c_01, c_11, c_21, c_31, c_40, c_50, etc.
The transition probability matrix is not vectorized; it is stored as four floats in the order p_00, p_01, p_10, p_11.

So the inner loop in the SSE function consists of two halves, each having two blocks followed by two additions and a multiplication. Looking at the first block in the first half, it gets the condLikes for the first state of four characters in the left child and the right child, and then multiply each of them with the transition probability of staying in state 0 (p_00). Then we get the condLikes for the second state at the child nodes, and multiply them with the probability of starting with state 0 at the parent, and ending with state 1 in each child. These probabilities are then added together separately for the left and the right child, and then the left and right probabilities are multiplied together to get the cond likes of state 0 of four characters at the parent node. Similar logic for the second half of the inner loop.

@kusalananda : Please mark this issue as resolved, unless you find any additional problems.

**Comment by kusalananda** [comment]
Thanks for the thorough testing! I find no additional issues. Any feature branch related to this issue will be deleted. This issue is now closed.
