### ISSUE TITLE
Segmentation fault when quitting

### ISSUE THREAD

**Issue by zhangchicool** [NBISweden/MrBayes#36]
With the attached example:
1. run mrbayes: ./mb
2. run command: exe test.nex
3. quite: q
--> Segmentation fault: 11

It seems FreeModel() in model.c is to blame, especially line 12378 with
            for (j = 0; i < numGlobalChains; ++j)
in which i seems should be j. But changing it didn't solve the issue...
 
[test.nex.zip](https://github.com/NBISweden/MrBayes/files/564502/test.nex.zip)

**Comment by kusalananda** [comment]
Hi Chi!

The loop conditional is wrong, yes.  Changing it from `i` to `j` results in an attempt to free unallocated memory (a new issue). I commented out the loop completely. I introduced it when I was hunting memory leaks as the `tree` member of the `params` struct is never freed completely as far as I can see.
