### ISSUE TITLE
Update formula in HomeBrew science

### ISSUE THREAD

**Issue by zhangchicool** [NBISweden/MrBayes#37]
Update the mrbayes formula in HomeBrew science
https://github.com/Homebrew/homebrew-science/blob/master/mrbayes.rb
after 3.2.7 is released.

**Comment by nylander** [comment]
HomeBrew science is deprecated. Need to seek alternative channels for incorporating mb in homebrew.

**Comment by kusalananda** [comment]
@zhangchicool Could you send me a copy of the most recent HomeBrew formula? The above link is no longer working.

**Comment by zhangchicool** [comment]
Since HomeBrew science is deprecated, I think we should just close this issue.

**Comment by kusalananda** [comment]
We still want to check whether we can provide a HomeBrew formula for Mac users...

**Comment by zhangchicool** [comment]
I find the latest formula is at https://github.com/brewsci/homebrew-bio/blob/master/Formula/mrbayes.rb

**Comment by nylander** [comment]
Latest homebrew formula now points to 3.2.7a.
Closing.
