### ISSUE TITLE
Poor mixing / no convergence for covarion model

### ISSUE THREAD

**Issue by zhangchicool** [NBISweden/MrBayes#44]
I'm running mrbayes 3.2.5. I'm having trouble with getting to convergence with the covarion model on. It seems to be caused by very poor mixing of the s(off->on) and s(on->off) parameter associated with the covarion parameter.

What happens during my run is that split frequencies slowly decrease to perhaps 0.02 where after they shoot off to 0.4 and never come down again. I tested this for 10 runs and in 4 of the cases the jump in split frequencies occurred. Setting covarion=off solves this problem (see split_freq_covarion_ON.png and split_freq_covarion_off.png). I then looked the traces for the different parameters using tracer. For the s(off->on) and s(on->off) parameter very poor mixing is seen even for the 6 runs that do convergence below a split frequency of 0.01 (see trace_s_off_to_on.png).
I've attached output files for two runs with covarion on. One of them makes it below 0.01, the other one doesn't. I've also attached the commands.nex file and a multiple alignment (msa.nexus) with gap encoding.

Thanks for looking into this and let me know if I can be of further help.
Chris

[covarion_bug.zip](https://github.com/NBISweden/MrBayes/files/782904/covarion_bug.zip)
(https://sourceforge.net/p/mrbayes/bugs/1628)

**Comment by nylander** [comment]
This may be related to issue #229. Continue on that issue.
