### ISSUE TITLE
MPI job stopped without warnings when sequences are large

### ISSUE THREAD

**Issue by zhangchicool** [NBISweden/MrBayes#45]
I tested running mb commands as in 43ubuntu10_int_NEX2.nex attached. It was ok for a subset of my original file, 43ubuntu10_test2_nex_space.nex (nchar=120) (see mpirun.o3675846), but for my full 1GB file, the run was stuck in loading data matrix (see mpirun.o3675054 for the interactive output of the 1GB file, but nothing in an error file).
The 1GB file has ~280000 sequence blocks of 43 taxa (50 bp per block). The following is commands I submitted openmpi job in sun grid engine (University's cluster).
$-bash-4.1$ qsub -cwd -pe smp 4 -b y mpirun -np 8 --mca btl_tcp_if_include p120p2 mb -i 43ubuntu10_int_NEX2.nex
Your job 3675846 ("mpirun") has been submitted
I compiled mb source code with ./configure --with-beagle=no --enable-mpi=yes. I attached config.log file here. Thankyou for your clarification.
Regards, Weerachai

[question.zip](https://github.com/NBISweden/MrBayes/files/782912/question.zip)
(https://sourceforge.net/p/mrbayes/bugs/1633)

**Comment by nylander** [comment]
Most probably due to memory issues (lack of RAM?). 14,000,000 bp per taxon is a large matrix.
Program should warn for this, however (see #67 )

**Comment by nylander** [comment]
closing. Memory check would be a good feature to implement. See #67
