### ISSUE TITLE
Continuous datatype

### ISSUE THREAD

**Issue by zhangchicool** [NBISweden/MrBayes#47]
I tried to analyze continuous characters on MrBayes 3.1.2 and 3.2 on Windows XP and Windows 7.
The command file (attached to this message) is read without problems but when i start the chains the program closes.
Windows XP returns this error codes:
AppName: mrbayes.exe AppVer: 0.0.0.0 ModName: mrbayes.exe ModVer: 0.0.0.0 Offset: 000c08e0

[continuous.nex.zip](https://github.com/NBISweden/MrBayes/files/782931/continuous.nex.zip)

**Comment by zhangchicool** [comment]
MrBayes reads in continuous characters but there is no code to compute likelihoods. The program should report an error though, instead of crashing. We will look at this. -- Fredrik

**Comment by zhangchicool** [comment]
It might be useful to support continuous traits. I guess if we assume that the traits are independent, the likelihood should be straightforward to calculate (multiplication of normal densities?). I am not sure although.

**Comment by nylander** [comment]
Awaiting the merging of code in pull request #142

**Comment by andkaha** [comment]
The code merged with PR #142 disallows the use of the "Continuous" datatype. That PR closed issue #135, does it also close this issue?

**Comment by nylander** [comment]
MrBayes now warns (and exits) if continuous characters are read. Future versions may support this data type. Closing this issue for now.
