### ISSUE TITLE
Segmentation Fault when setting constraints in a very large tree

### ISSUE THREAD

**Issue by zhangchicool** [NBISweden/MrBayes#48]
I am using [PASTIS](http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12117/abstract) to generate a very large tree for comparative analysis. If I run the file generated by PASTIS on mrbayes v.3.2.6, I get a Segmentation Fault Error. This has happened using both the serial and mpi versions on a Mac and a Linux cluster.

I believe this might be due to the number of tips in the phylogeny (>300K), since even a file with a very simple constraint (attached) reproduces the error, and there is no error if I use the same file with just a few tips. The chain starts if I use the uniform topology prior, and the error happens exactly when setting constraints as the topology prior. Is there any workaround this issue?

I am attaching both the nexus file that generates the error and the output log.

Thanks,
Bruno

[constraint.zip](https://github.com/NBISweden/MrBayes/files/782940/constraint.zip)
(https://sourceforge.net/p/mrbayes/bugs/1642)

**Comment by nylander** [comment]
Probably due to memory issues (lack of RAM)? Please monitor memory consumption on execution of file.
Of course, the program should warn about this (see #67 )

**Comment by nylander** [comment]
Closing
