### ISSUE TITLE
Support BEAGLE v3.0 in MrBayes v3.2.7 and newer

### ISSUE THREAD

**Issue by zhangchicool** [NBISweden/MrBayes#52]
Migrate the code from https://github.com/ayresdl/mrbayes-beagle3 into develop branch

**Comment by nylander** [comment]
This would have been done by now (plus/minus some potential issues  #100)? Ready to close @kusalananda?

**Comment by andkaha** [comment]
Yes. Closing this. I'm slow on closing issues.
