### ISSUE TITLE
nswaps has no effect (easy fix)

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#57]
Transferred from https://sourceforge.net/p/mrbayes/bugs/1654/
Created: 2017-11-08
Creator: thomas fisher-york

In mcmc.c, the outer pair of brackets in the following were missing, so only attempted swap once, independent of what chainParams.numSwaps was set to:

for (j = 0; j<chainParams.numSwaps; j++)
{ // Add this pair of brackets
    GetSwappers (&swapA, &swapB, i);
    if (AttemptSwap (swapA, swapB, seed) == ERROR)
    {
        MrBayesPrint ("%s Unsuccessful swap of states\n", spacer);
        if defined (MPI_ENABLED)
            nErrors++;
        else
            return ERROR;
        endif
     }
} // Add this pair of brackets

**Comment by kusalananda** [comment]
This code has already been fixed by Chi on 2017-11-22 16:55:26 in commit 8a9adb11.
