### ISSUE TITLE
Six state limit for ordered morphological characters

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#61]
Transferred fom https://sourceforge.net/p/mrbayes/bugs/1651/

Created: 2017-06-06
Creator: Steven Heritage

Hello,

Our lab uses MrBayes regularly and we find the flexibility and reliability of the software makes it the premium choice for phylogenetic inference. You’ve done a very nice job over the years and we truly appreciate it! These days, our most common type of analysis involves combined DNA and morphological data from living and fossil taxa. However, we often hit a limitation which (to our knowledge) is not mentioned in the MrBayes documentation. The MrBayes team may not consider it a “bug” but it has caused much frustration in our group and I’m sure other users have experienced it too.

In version 3.2.6, morphological data can be coded in ten states (0-9). However, if a morphological character is set as ordered, the limit is six states (0-5). Our data sets have hundreds of ordered morphological characters, many of which are scored with more than six states.

In order to proceed with analysis, we have to recode characters. For instance, if an ordered character is scored with eight discrete states (0-7), we must recode that character using four states where: 0=(old 0&1), 1=(old 2&3), 2=(old 4&5), 3=(old 6&7). This is not ideal and almost certainly loses phylogenetic information. In some cases rare fossils are already represented by limited data and it’s a shame to effectively mask some distinguishing character scores during recoding.

Another situation arises when we use “intermediate scoring” rather than “polymorphic scoring” to code for ordered morphological characters. This method is common in paleontological data sets like ours. For instance, if there are five discrete states for a character and those occur on an ordinal scale, we use the scores 0, 2, 4, 6 & 8 to represent the discrete states. If specimens for a taxon are polymorphic for those states, we code that taxon with an intermediate score… for example 0&2 are coded as 1. This method retains some phylogenetic information that would be effectively ignored during tree search if we instead used polymorphic state combinations in the range of 0-4. However, to get data to work with MrBayes we must recode these types of characters as follows: 0=(old 0), 0&1=(old 1), 1=(old 2), 1&2=(old 3), 2=(old 4), 2&3=(old 5), 3=(old 6), 3&4=(old 7), 4=(old 8).

These workarounds to the “six state limit for ordered characters” are operative but in many cases omit (and mask) phylogenetic signal that could be useful during inference. In a recent data set, we gained ~5,000 polymorphic-scored cells in a labor intensive recoding effort.

In a future version, would you please consider lifting the six state limit for ordered morphological characters? This would be so helpful! Other likelihood based software (RAxML for example) has no limit on ordered characters and allows 36 morphological states (0-9, A-Z). Lifting this limitation (and even expanding the number of possible states up to 20 or more) would contribute to a nice list of features that, in our opinion, makes MrBayes the best phylogenetic inference platform to analyze diverse data sets.

Thanks again for the great software!

Cheers,
Steven

**Comment by ronquist** [comment]
This feature requires a fair bit of coding and I suspect that the user community benefiting from it would be small. Chi has expanded the state space to 36 states, I think, so part of the enhancement is already taken care of when his pull request is granted.

**Comment by zhangchicool** [comment]
I updated the pull request #145. It now supports up to 24 states (0-9 and A-N) actually.

**Comment by ronquist** [comment]
I have considered the possibility of extending the support for ordered characters to more than six states. However, this requires a fair amount of coding given the current way things are set up in MrBayes. It is relatively straight-forward to run equivalent analyses, with ordered characters that have arbitrary number of states, in RevBayes, so I am uncertain about the need to support this in MrBayes. I will close this issue now; if this feature request is added back in, I will consider it seriously.

**Comment by jrwmain-source** [comment]
> It is relatively straight-forward to run equivalent analyses, with ordered characters that have arbitrary number of states...

But will splitting an ordered character change how Bayes treats the data, e.g, accepting the separate additives having a different distribution of evolutionary rates, which sounds bad. Is it less optimal than 2+ characters with >6 states?

**Comment by jrwmain-source** [comment]
@ronquist

**Comment by zhangchicool** [comment]
I have extended the support for ordered characters to more than 6 states (up to 24), see 182ab3e16f5a977e8d9acc39683018ddb110c1a9 at https://github.com/zhangchicool/MrBayes

**Comment by jrwmain-source** [comment]
@zhangchicool Thank you so much! This will be a great help to me and my colleagues trapped in the Morphology Zone, lol.
