### ISSUE TITLE
Error appending

### ISSUE THREAD

**Issue by ajnarivera** [NBISweden/MrBayes#68]
I'm running version 3.2.6 and when I try to append to an existing run I get one of two errors:
1) If I keep all files generated as is, I get the error 
Error in appending to previous run
Error in command "Mcmc"

The error is in the character "n" in the command mcmc ngen=120000000

2) If I paste the .ckp file output into the nexus infile I get the errors 
Could not find parameter 'alpha': ignoring values
and 
Could not find move 'multiplier(alpha)'

**Comment by nylander** [comment]
Could not reproduce this with v.3.2.7:
`exe data.nex;
mcmc nruns=1 ngen=10000 checkpoint=yes checkfreq=1000;
mcmc nruns=1 ngen=20000 checkpoint=yes checkfreq=1000 startparams=current starttree=current append=yes;`
