### ISSUE TITLE
mpi run, processors have sent help message

### ISSUE THREAD

**Issue by mwille2** [NBISweden/MrBayes#69]
Hi,
I'm trying to rerun an old tree using the mpi version of mrbayes, but on a different server. I've recently installed mr bayes. 
I've tried initiated the command file on the normal mrbayes to make sure there are no issues, but when trying to actually run it using mpi bayes I get the error below. I've tried to run it with different numbers of cores, but the result is the same, perhaps suggesting there is an issue with the mpi function? Not a problem Ive ever had with mpi my bayes before.
Thanks for your help!
Michelle

"[[43212,1],2]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: vidrlmodel

Another transport will be used instead, although this may result in
lower performance."

AND

"There must be at least as many chains as MPI processors"

AND

"
[vidrlmodel:23748] 11 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[vidrlmodel:23748] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages"

**Comment by nylander** [comment]
Hi, we can not go further without knowing the which MrBayes version and how it was compiled (openmpi version etc), how the `mcmcp` or `mcmc` commands looked like, and which command you used to start the run ("`mpirun ...`").
One, black-magic-, suggestion to overcome problems similar to yours was to add these arguments to your `mpirun` command: `-mca btl ^openib`. Untested by us, however.
/J

**Comment by mwille2** [comment]
Hi Johan,
I meant to close the problem, as I solved it by uninstalling, installing a different openmpi compiler and subsequently reinstalling mrbayes (although it took a few tries to get it right). 
Sincerely,
Michelle
