### ISSUE TITLE
Binaries present in the ".tar.gz" releases file

### ISSUE THREAD

**Issue by StuntsPT** [NBISweden/MrBayes#71]
In the releases page, at least for [version 3.2.6](https://github.com/NBISweden/MrBayes/archive/v3.2.6.tar.gz), the file `v3.2.6.tar.gz` contains binaries for windows and OSX.
I expected only source code to be found there. Is this intended? It has forced me to work some hoops when [packaging it for Arch Linux](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mrbayes#n18), plus make the source download a lot larger than it needed to be.
Thank you for taking a look at it.

**Comment by kusalananda** [comment]
The release Zip file for version 3.2.6 contains both source code (in a `tar` archive) as well as binaries for macOS and Windows, yes. The project was moved over to GitHub from Sourceforge after that release and the repository for older releases (even 3.2.6 which is the latest _real_ release) may well be a bit weird. 

I suggest that you instead look at the 3.2.7 prerelease. We've been in contact with the Debian maintainer and he says that builds fine with the Debian package building process.  We are looking at making a proper 3.2.7 release after the summer.

**Comment by StuntsPT** [comment]
Hi @kusalananda , and thank you for your reply.
Yes, the difference between 3.2.6 from github and sourceforge is just the directory structure. It is kind of weird to have nested `.tar.gz` files. I have worked around it in the `PKGBUILD`, but I just though I should alert you to it (in the unlikely event you were not aware).
As for `3.2.7` prerelease, the structure is looking great (I'd argue that the new structure is *way* better than what was on sourceforge). It also builds and runs as expected under an ArchLinux `PKGBUILD` (which is also much simpler than for version `3.2.6`).

I'll be waiting for your post-Summer release. =-)

Best,

Francisco
