### ISSUE TITLE
Investigate whether the automake macro `AX_EXT` supports the Intel `icc` compiler.

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/MrBayes#77]
We seem to get warnings like

```
option '-mfma' ignored, suggest using '-march=core-avx2'
```

while configuring the build using the `icc` and `mpiicc` compilers.

**Comment by kusalananda** [comment]
Have contacted someone who's been involved in writing the `AX_EXT` macro to get clarification and possibly help in updating the macro.

**Comment by kusalananda** [comment]
I will try to manually change the relevant options if `icc` is detected.

**Comment by andkaha** [comment]
We don't have the time or motivation to do anything about this. If a user wants special support of `icc`, they will need to contact us.
