### ISSUE TITLE
infering Ancestral states of all ancestors on tree and without constraints 

### ISSUE THREAD

**Issue by inbal-tz** [NBISweden/MrBayes#80]
hi
I have a binary data set and would like to infer the ancestral states of all ancestors on the tree. also I would like to do so without constraining the tree. is there a way to do so?
thanks

**Comment by nylander** [comment]
No, that's not possible. Please see p. 78  in the Manual_MrBayes_v3.2.pdf on how to perform the analysis. A helper tool for summarizing the output can be found here: https://github.com/nylander/Parse_MrBayes_Ancestral_States
/Johan
