### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/MrBayes#81]
We should use them.

See e.g. NBIS LocalEGA project.

**Comment by viklund** [comment]
[Here](https://github.com/NBISweden/LocalEGA/tree/dev/.github) are the templates for the LocalEGA project.

**Comment by kusalananda** [comment]
Preliminary template added.  Need feedback on this and whether we'd like to split this into separate "Bug report", "Feature request" and "Support issue" templates (I think this is a good idea, and we can do this as the LocalEGA has done it too, which looks nice).

**Comment by kusalananda** [comment]
Issue templates now split into

* Bug reports
* Internal issues
* Support requests

**Comment by nylander** [comment]
Looks good to me. Great that you added disclaimer about (lack of) usage support.
@kusalananda, I say commit!

**Comment by kusalananda** [comment]
If further changes have to be made to the templates, then just make those changes and commit them, or submit a PR if you want feedback (or we'll chat on Slack).
