### ISSUE TITLE
Incorrect format for printing default values in `h mcmc`

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#82]
Command `h mcmc` outputs 

```
Reweight        <number>,<number>     0.00 v 0.00 ^
```

Expected output:

```
Reweight        <number>,<number>     0.00,0.00
```
or

```
Reweight        <number>,<number>     0.00,0.00,0.00
```

**Comment by nylander** [comment]
Pull request #120  will hopefully solve this

**Comment by andkaha** [comment]
I didn't spot what change in PR #120 affected this. Could you point it out to me?

**Comment by nylander** [comment]
Should be line 14005 in https://github.com/NBISweden/MrBayes/blob/spell/src/command.c

**Comment by andkaha** [comment]
PR #120 closes this.
