### ISSUE TITLE
MacOS Mojave ln: libedit.3.dylib‍: Operation not permitted

### ISSUE THREAD

**Issue by TBrunes** [NBISweden/MrBayes#89]
Previously, you added the following note in the file ReadMe-MAC.rtf of Mac version of MrBayes 3.2:

2. The 64bit executable "mb" might fail to lunch on OS X 10.6 (snow leapord) with error : dyld: Library not loaded: /usr/lib/libedit.3.dylib‍
There is an easy fix by typing the following commands in terminal:
    cd /usr/lib 
    sudo ln -s libedit.2.dylib libedit.3.dylib‍

However, in the latest MacOS version (Mojave) this operation is not permitted:

ln: libedit.3.dylib‍: Operation not permitted

I did some research and this error is probably related to the SIP (System Integrity Protection).

Do you have any idea of how to figure out this problem?

Thank you in advance,

Tuliana Brunes

**Comment by kusalananda** [comment]
I'm assuming you are using a pre-compiled version of MrBayes?

That advice was (IMHO) ill advised to start with, and we certainly don't want users disabling SIP on their macOS systems.

I'm using macOS Mojave myself, and my system has both `libedit.2.dylib` and `libedit.3.dylib` in `/usr/lib`.  Could you please confirm what the actual error is that you get when running MrBayes (the verbatim error message) and also confirm whether this is a pre-built binary (and what the version is)?

Thanks,
Andreas

**Comment by TBrunes** [comment]
First, thank you, Andreas.

I'm trying to use the parallel version of the binary (MrBayes 3.2.6) compiled using the OpenMPI environment.

I followed all the steps of the file ReadMe-MAC.rtf

Did I answer your questions correctly?

**Comment by kusalananda** [comment]
Hi again,

It would be nice to be able to se the actual error message as well.

**Comment by TBrunes** [comment]
MacBook-Pro-de-Tuliana:mrbayes_os brunes$ mpirun -np 2  mb-mpi
dyld: Library not loaded: /usr/local/lib/libhmsbeagle.1.dylib
  Referenced from: /Users/brunes/documents/science/programas/mrbayes_os/mb-mpi
  Reason: image not found
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
dyld: Library not loaded: /usr/local/lib/libhmsbeagle.1.dylib
  Referenced from: /Users/brunes/documents/science/programas/mrbayes_os/mb-mpi
  Reason: image not found

**Comment by TBrunes** [comment]
### MacBook-Pro-de-Tuliana:mrbayes_os brunes$ mpirun -np 2  mb-mpi
dyld: Library not loaded: /usr/local/lib/libhmsbeagle.1.dylib
  Referenced from: /Users/brunes/documents/science/programas/mrbayes_os/mb-mpi
  Reason: image not found
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
dyld: Library not loaded: /usr/local/lib/libhmsbeagle.1.dylib
  Referenced from: /Users/brunes/documents/science/programas/mrbayes_os/mb-mpi
  Reason: image not found

**Comment by TBrunes** [comment]
MacBook-Pro-de-Tuliana:mrbayes_os brunes$ mpirun -np 2  mb-mpi
dyld: Library not loaded: /usr/local/lib/libhmsbeagle.1.dylib
  Referenced from: /Users/brunes/documents/science/programas/mrbayes_os/mb-mpi
  Reason: image not found
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
dyld: Library not loaded: /usr/local/lib/libhmsbeagle.1.dylib
  Referenced from: /Users/brunes/documents/science/programas/mrbayes_os/mb-mpi
  Reason: image not found

**Comment by kusalananda** [comment]
That has nothing to do with `libedit`, it's the fact that the Beagle library is not installed.

The corresponding version of the Beagle library that has to be installed is release 2.1.2, and there is an installer for macOS available from a link on the Beagle library's GitHub page (https://github.com/beagle-dev/beagle-lib).

The link to the installer is https://www.dropbox.com/s/11kgt2jlq3lzln3/BEAGLE-2.1.2.pkg

**Comment by TBrunes** [comment]
It's running now.

Thank you and excuse the confusion.

Best.
