### ISSUE TITLE
feature/random_number_cleanup

### ISSUE THREAD

**Issue by ronquist** [NBISweden/MrBayes#9]
@kusalananda : I have looked at the changes introduced in random_number_cleanup feature branch.

Replacing the existing random number generator with a system-provided generator is not a good idea in my view. There is no guarantee that a system-provided generator will produce the same series of random numbers on different machines even if the same seed is used, as far as I can tell. This could potentially be extremely frustrating when trying to reproduce bugs that occur very rarely during MCMC simulation.

In addition, I can find no information on the web on the new random() function. It does not appear to be part of the C standard. Presumably it is a recent non-standard addition to one of (or some of) the C libraries (it seems that it is a POSIX standard), or it is in the C++ standard and not in the C standard (I may be wrong; please inform me if so). We tend to avoid such non-standard functions in MrBayes.

There are also several serious problems with the new code in the MPI version. First, the series produced off of globalSeed, and used for everything but swaps (and run stamps), produces the same series of random numbers for each parallel chain, because the offset tactic ("seed = globalSeed + proc_id" in mcmc.c) used in the original code to produce unique series of random numbers for each processor now is defunct. So all parallel chains with the same temperature will do exactly the same thing, as far as I can tell. Even worse, the current MPI swap mechanism relies on all chains being able to generate exactly the same sequence of random numbers off of the swapSeed seed to be able to figure out how to swap values. Since no seed is used in the new RandomNumber function, the MPI version would surely crash pretty soon because different processors would be confused over how to swap values as they generate different swapA and swapB values (see GetSwappers and AttemptSwap functions in mcmc.c).

It is possible to address both the MPI swapping problem and the MPI identical random number sequence problems in several ways, using either system RNG's or user-specified RNG's like the one we use now in MrBayes. They will require a fair amount of programming however. There are several better RNG's available that could replace the current one, including for instance the Mersenne Twister, which I think is the one used in R, and many other statistics software packages, I think. I would rather do this than shift to a system-provided RNG. If it costs 10 % in performance, I would not be worried. I would take even worse hits before seriously considering a system-provided RNG.

There are several additional problems with this particular feature branch, which would have to be corrected before it were merged with the rest of the code. I am sure you are aware of these, but just for the record:

1. The RandomNumber function in utils. c has an incorrect header comment, this needs to be corrected.

2. RandomNumber function is not using its argument. The declaration of RandomNumber should be changed accordingly and no calls to the function should pass a non-used argument.

3. A note about any change to the RandomNumber function should be added to the comment header of the RandomNumber function.

4. The old code in the #if 0 block should be removed, or at least commented clearly.

5. The swapSeed, runIDSeed and globalSeed would have to be merged and all the interface functionality changed to reflect this, for instance in the info output about the run, in the "set" command, in the help info for the "set" command etc.

/Fredrik

**Comment by kusalananda** [comment]
Hi Fredrik,

Thanks for your clarifications and input!

When creating this set feature branches (random number, complex arithmetics, and the general "cleanup" feature branch), I was mainly concerned with improving the speed of execution. Since some of the changes conflicts with the now stated aims of the code, that is, C11-conformance and reproducibility across hardware and software platforms, it is absolutely clear that there is no way that they will ever go into the `develop` branch.

This feature branch in particular will be deleted in its entirety since it relies on a POSIX extension to the C99 standard. I will delete it as soon as I've had time to look at your other comments.

Regards,
Andreas

**Comment by kusalananda** [comment]
Branch is now deleted.
