### ISSUE TITLE
Error in command partition ocurred when the program reads ";" at the end of the command

### ISSUE THREAD

**Issue by VictorHJD** [NBISweden/MrBayes#97]
Hi!
I am currently trying to run a tree with 32 partitions. I am including the mrbayes block directly in my alignment in nexus format; however when I execute the file it stops after defining the charset in the command partition 

 Reading mrbayes block
      Defining charset called 'Eim_Nuc375_Nuc376'
      Defining charset called 'Eim_Nuc1339_Nuc1340'
      Defining charset called 'Eim_Nuc2173_Nuc2174'
      Defining charset called 'Eim_Nuc3283_Nuc3284'
      Defining charset called 'Eim_Nuc3835_Nuc3836'
      Defining charset called 'Eim_Nuc5051_Nuc5052'
      Defining charset called 'Eim_Nuc5999_Nuc6000'
      Defining charset called 'Eim_Nuc6075_Nuc6076'
      Defining charset called 'Eim_Nuc6323_Nuc6324'
      Defining charset called 'Eim_Nuc6819_Nuc6820'
      Defining charset called 'Eim_Nuc7975_Nuc7976'
      Defining charset called 'Eim_Nuc8427_Nuc8428'
      Defining charset called 'Eim_Nuc8939_Nuc8940'
      Defining charset called 'Eim_Nuc9133_Nuc9134'
      Defining charset called 'Eim_Nuc9409_Nuc9410'
      Defining charset called 'Eim_Nuc10085_Nuc10086'
      Defining charset called 'Eim_Nuc3665_Nuc3666'
      Defining charset called 'Eim_Nuc4783_Nuc4784'
      Defining charset called 'Eim_Nuc9135_Nuc9136'
      Defining charset called 'Eim_Nuc445_Nuc446'
      Defining charset called 'Eim_Nuc1429_Nuc1430'
      Defining charset called 'Eim_Nuc3173_Nuc3174'
      Defining charset called 'Eim_Nuc3707_Nuc3708'
      Defining charset called 'Eim_Nuc6133_Nuc6134'
      Defining charset called 'Eim_Nuc7249_Nuc7250'
      Defining charset called 'Eim_Nuc7585_Nuc7586'
      Defining charset called 'Eim_Nuc8331_Nuc8332'
      Defining charset called 'Eim_Nuc8631_Nuc8632'
      Defining charset called 'Eim_Nuc8955_Nuc8956'
      Defining charset called 'Eim_Nuc8971_Nuc8972'
      Defining charset called 'Eim_Nuc9059_Nuc9060'
      Defining charset called 'Eim_Nuc9209_Nuc9210'
      Setting autoclose to yes
      Setting nowarnings to yes
      Defining partition called 'multimarker'
      Character 2 not included in partition
      Error in command "Partition"
      There was an error on at least one processor
      The error occurred when reading char. 666-666 on line 95
         in the file '/SAN/Victors_playground/mouseGT/combinedEfalNucFrame_Nuc.nex'

The character found in the position marked as problematic is ";" , I retyped but still don't work.  

I am using MrBayes 3.2.7

Do you have any idea of what could be happening

**Comment by nylander** [comment]
Dear VictorHJD,
Thank you for your report. The message `Character 2 not included in partition` might indicate that not all characters in your input are assigned to partitions. Maybe the position assignments for the partitions need to be double (triple) checked?
/J

**Comment by nylander** [comment]
Closing
