### ISSUE TITLE
Compiler warnings in later versions of gcc

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#98]
## Warnings and Notes from gcc v.8.2.0

Compiling branch feature/beagle3 (latest commit ` c91de61472fd7dd3758171e002fceb68b5f8dde0`) using gcc (Debian 8.2.0-14) 8.2.0, we see more compile **warnings** and **"notes"**. Those should be considered.

A few examples:

`-Wstringop-truncation` complains when
```
command.c:3554:5: warning: 'strncpy' output may be truncated copying 98 bytes from a string of length 99 [-Wstringop-truncation]
    strncpy (exeFileName, inputFileName, 98);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

`-Wmaybe-uninitialized` complains when
```
mbbeagle.c:2618:33: warning: 'nStates' may be used uninitialized in this function [-Wmaybe-uninitialized]
    int         i, j, d, c = 0, nStates, beagleReturn, site, dIndex, divisionOffset;
                                ^~~~~~~
```
`-Wformat-overflow=` complains when
```
mcmc.c:15950:52: warning: '%d' directive writing between 1 and 10 bytes into a region of size between 3 and 210 [-Wformat-overflow=]
                sprintf (fileName, "%s%s.tree%d.run%d.t", workingDir, localFileName, i+1, n+1);
```

`-Wrestrict` complains when
```
utils.c:311:9: warning: 'strncpy' accessing between 0 and 2147483647 bytes at offsets [-2147483636, 2147483649] and 0 may overlap up to 11 bytes at offset 10 [-Wrestrict]
        strncpy (strCpy,strBuf,longestLine);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kusalananda** [comment]
It looks like it's doing static analysis. Good. I will look at these and increase the mentioned buffers to the correct sizes, or limit the possible sizes of the written data.  I fixed a bunch of these types of issues found by the Clang static analyser a few months ago too.

**Comment by andkaha** [comment]
Although PR #121 did not touch the actual lines mentioned in this issue, I get no further warnings from GCC 8 for any of the code.
